jQuery(document).ready(function(){"use strict";var $elementor_panel=jQuery('#elementor-panel');if(TRX_ADDONS_STORAGE['add_hide_on_xxx']=='replace'){jQuery('body').addClass('replace_hide_on_xxx');}
var editing_el=false,pmv=false;$elementor_panel.on('change.trx_addons_refresh_list','select[data-setting*="post_type"],select[data-setting*="taxonomy"]',function(e){var $refresh_obj=jQuery(this),$fld=false,post_type='',cat_flds=[],found=false,editing_obj=editing_el;if($refresh_obj.data('setting').indexOf('post_type')===0){$refresh_obj.parents('.elementor-control').nextAll().each(function(){if(found)return;$fld=jQuery(this).find('select[data-setting*="taxonomy"],select[data-setting*="parent_post"]');if($fld.length>0){cat_flds.push($fld);if($fld.data('setting').indexOf('taxonomy_')>=0){found=true;}}});}else if($refresh_obj.data('setting').indexOf('taxonomy')>=0){$refresh_obj.parents('.elementor-control').prevAll().each(function(){if(post_type)return;$fld=jQuery(this).find('select[data-setting*="post_type"]');if($fld.length>0){post_type=$fld.val();}});cat_flds=[$refresh_obj.parents('.elementor-control').next().find('select')];}
if(cat_flds.length>0){var num=0;jQuery.each(cat_flds,function(index,$cat_fld){$cat_fld.each(function(){var $fld=jQuery(this);var $wrapper=$fld.parents('.elementor-control-field').eq(0),$lbl=jQuery('label.elementor-control-title',$wrapper);setTimeout(function(){var refresh_type=$fld.data('setting').indexOf('parent_post')>=0?'parent_posts':($fld.data('setting').indexOf('taxonomy')>=0?'taxonomies':'terms');trx_addons_refresh_list(refresh_type,$refresh_obj.val(),$fld,$lbl,undefined,editing_obj);},300*num);num++;});});}
return false;});if(window.elementor!==undefined&&window.elementor.hooks!==undefined){elementor.hooks.addAction('panel/open_editor/widget',trx_addons_elementor_open_panel);elementor.hooks.addAction('panel/open_editor/widget',trx_addons_elementor_refresh_layout_selector_link);elementor.hooks.addAction('panel/open_editor/widget',trx_addons_elementor_add_data_to_select2);}
if(window.top.$e!==undefined&&window.top.$e.routes!==undefined){window.top.$e.routes.on('run:after',function(component,route,args){if(route.indexOf('panel/editor/')===0){if(!editing_el||editing_el.view.cid!=args.view.cid){editing_el=args;pmv=false;}
if(pmv!==false){trx_addons_elementor_open_panel(pmv.panel,pmv.model,pmv.view,true);trx_addons_elementor_refresh_layout_selector_link(pmv.panel,pmv.model,pmv.view,true);trx_addons_elementor_add_data_to_select2(pmv.panel,pmv.model,pmv.view,true);}}});}else{$elementor_panel.on('click','.elementor-panel-navigation-tab span',function(){if(pmv!==false){trx_addons_elementor_open_panel(pmv.panel,pmv.model,pmv.view,true);trx_addons_elementor_refresh_layout_selector_link(pmv.panel,pmv.model,pmv.view,true);trx_addons_elementor_add_data_to_select2(pmv.panel,pmv.model,pmv.view,true);}});}
$elementor_panel.on('mouseup touchend','.elementor-repeater-tool-duplicate,.elementor-repeater-add',function(){if(pmv!==false){setTimeout(function(){trx_addons_elementor_refresh_layout_selector_link(pmv.panel,pmv.model,pmv.view,true);trx_addons_elementor_add_data_to_select2(pmv.panel,pmv.model,pmv.view,true);},10);}});function trx_addons_elementor_open_panel(panel,model,view,tab_chg){if(panel.content!==undefined){if(!tab_chg){pmv={'panel':panel,'model':model,'view':view};}
var $post_fld=panel.content.$el.find('select[data-setting*="post_type"]');var $parent_post_fld=panel.content.$el.find('select[data-setting*="parent_post"]');var $tax_fld=panel.content.$el.find('select[data-setting*="taxonomy"]');var $terms_fld=panel.content.$el.find('select[data-setting*="cat"],select[data-setting*="category"]');if($post_fld.length===0||$tax_fld.length===0||$terms_fld.length===0){return;}
var fields=[$post_fld,$parent_post_fld,$tax_fld,$terms_fld];var need_refresh=false;for(var i in fields){if(fields[i].length===0){continue;}
fields[i].each(function(){if(!need_refresh){var $fld=jQuery(this);need_refresh||=!trx_addons_elementor_check_list_values($fld,model.getSetting($fld.data('setting')));}});}
if(need_refresh){$post_fld.trigger('change.trx_addons_refresh_list');}}}
function trx_addons_elementor_check_list_values($fld,values){var found=true;if($fld.length>0&&typeof values!='undefined'&&values!==''){var parts=(''+values).split(',');for(var i=0;i<parts.length;i++){if(parts[i]!==''&&$fld.find('option[value="'+parts[i]+'"],option[value="'+parts[i]+' "]').length===0){found=false;break;}}}
return found;}
function trx_addons_elementor_add_data_to_select2(panel,model,view,tab_chg){if(panel.content!==undefined){var ids_fld=panel.content.$el.find('select[data-setting="ids"][type="select2"],select[data-setting="post"][type="select2"]');if(ids_fld.length>0){ids_fld.each(function(){var fld=jQuery(this);if(typeof fld.data('select2').dataAdapter.ajaxOptions!=='undefined'){fld.data('select2').dataAdapter.ajaxOptions.data=function(params){var controls=fld.parents('#elementor-controls'),terms=controls.find('select[data-setting="category"]').length>0?controls.find('select[data-setting="category"]').val():controls.find('select[data-setting="cat"]').val(),tax=controls.find('[data-setting="taxonomy"]').val(),parent_post=controls.find('[data-setting="parent_post"]').val(),pt=controls.find('[data-setting="post_type"]').val();return trx_addons_object_merge({nonce:TRX_ADDONS_STORAGE['ajax_nonce'],post_type:pt?pt:'',parent_post:parent_post?parent_post:'',taxonomy:tax?tax:'',terms:terms?(typeof terms=='array'||typeof terms=='object'?terms.join(','):terms):''},params);};}});}}}
$elementor_panel.on('change keyup','input[data-setting="_animation_delay"]'
+',input[data-setting="animation_delay"]'
+',select[data-setting="_animation"]'
+',select[data-setting="animation"]'
+',select[data-setting="_animation_duration"]'
+',select[data-setting="animation_duration"]'
+',select[data-setting="_animation_type"]'
+',input[data-setting="_animation_stagger"]',function(e){if(e.type=='change'||(e.type=='keyup'&&(e.keyCode==8||e.keyCode==46||(e.keyCode>=48&&e.keyCode<=57)||(e.keyCode>=96&&e.keyCode<=105)))){var preview=elementor.$preview[0].contentWindow;if(typeof preview.trx_addons_elementor_prepare_animate_items!='undefined'){setTimeout(function(){preview.trx_addons_elementor_prepare_animate_items(true,pmv.view.$el);},10);}}});function trx_addons_elementor_refresh_layout_selector_link(panel,model,view,tab_chg){if(panel.content!==undefined){panel.content.$el.find('a.trx_addons_post_editor').each(function(){trx_addons_layout_selector_refresh_link(jQuery(this));});}}
$elementor_panel.on('click','.elementor-panel-category-title',function(e){var cat=jQuery(this).closest('.elementor-panel-category').eq(0);setTimeout(function(){if(cat.hasClass('elementor-active')){var height=jQuery('#elementor-panel-elements-navigation').outerHeight()
+jQuery('#elementor-panel-elements-search-area').outerHeight(),skip=false;jQuery('#elementor-panel-categories > .elementor-panel-category').each(function(){if(skip||cat.attr('id')==jQuery(this).attr('id')){skip=true;return;}
height+=jQuery(this).outerHeight()+2;});jQuery('#elementor-panel-content-wrapper').scrollTop(height);}},300);});});(function(){"use strict";jQuery(window).on('elementor:init',function(){if(TRX_ADDONS_STORAGE['add_to_links_url']&&window.elementor&&window.elementor.hooks){var $elementor_panel=jQuery('#elementor-panel');if($elementor_panel.length){var trx_addons_add_extra_args_to_links_throttle=trx_addons_throttle(function($cont){if($cont===undefined)$cont=$elementor_panel;trx_addons_add_extra_args_to_links(TRX_ADDONS_STORAGE['add_to_links_url'],$cont);},500,true);function trx_addons_add_extra_args_to_links_hook(arg){trx_addons_add_extra_args_to_links_throttle();return arg;}
elementor.hooks.addFilter('panel/elements/regionViews',trx_addons_add_extra_args_to_links_hook);elementor.hooks.addFilter('editor/style/styleText',trx_addons_add_extra_args_to_links_hook);elementor.hooks.addFilter('controls/base/behaviors',trx_addons_add_extra_args_to_links_hook);$elementor_panel.on('mousedown touchstart click','.elementor-header-button',function(e){trx_addons_add_extra_args_to_links_throttle();});$elementor_panel.on('mousedown touchstart click','.elementor-panel-navigation-tab',function(e){trx_addons_add_extra_args_to_links_throttle();});}
if(typeof TRX_ADDONS_STORAGE['add_to_links_url']!='undefined'){if(typeof jQuery(document).ajaxComplete!='undefined'){jQuery(document).ajaxComplete(function(event,xhr,settings){if(typeof settings=='object'&&typeof settings.url=='string'&&settings.url===TRX_ADDONS_STORAGE['ajax_url']&&typeof settings.data=='string'&&settings.data.indexOf('get_library_data')>0){setTimeout(function(){var $library=jQuery('#elementor-template-library-modal');if($library.length){trx_addons_add_extra_args_to_links(TRX_ADDONS_STORAGE['add_to_links_url'],$library);if(!$library.hasClass('trx_addons_aff_inited')){$library.addClass('trx_addons_aff_inited').on('click touchstart mousedown','.elementor-template-library-menu-item,'
+'.elementor-template-library-template-preview,'
+'#elementor-template-library-header-preview-back',function(){trx_addons_add_extra_args_to_links_throttle($library);});}}},3000);}});}}}});window.trx_addons_get_settings_icon=function(icon){return typeof icon=='object'?(typeof icon['icon']!='undefined'?icon['icon']:''):icon;};window.trx_addons_get_socials_links=function(icons,style,show){var output='',show_icons=show.indexOf('icons')>=0,show_names=show.indexOf('names')>=0;if(icons.length>0&&typeof icons[0].name!='undefined'){var sn='',fn='',title='',url='';for(var i=0;i<icons.length;i++){sn=trx_addons_get_settings_icon(icons[i].name);fn=style=='icons'?sn.replace('trx_addons_icon-','').replace('icon-',''):trx_addons_get_basename(sn);title=icons[i].title!==''?icons[i].title:trx_addons_proper(fn);url=icons[i].url;if(trx_addons_is_off(url))continue;output+='<a target="_blank" href="'+url+'"'
+' class="social_item social_item_style_'+style+' sc_icon_type_'+style+' social_item_type_'+show+'">'
+(show_icons?'<span class="social_icon social_icon_'+fn+'"'
+(style=='bg'?' style="background-image: url('+sn+');"':'')
+'>'
+(!show_names?'<span class="screen-reader-text">'+title+'</span>':'')
+(style=='icons'?'<span class="'+sn+'"></span>':(style=='svg'?'<object type="image/svg+xml" data="'+sn+'" border="0"></object>':(style=='images'?'<img src="'+sn+'" alt="'+title+'" />':'<span class="social_hover" style="background-image: url('+sn+');"></span>')))
+'</span>':'')
+(show_names?'<span class="social_name social_'+fn+'">'+title+'</span>':'')
+'</a>';}}
return output;};window.trx_addons_elm_prepare_global_params=function(args,clear){for(var k in args){if(typeof args[k]=='object'){if(k=='__globals__'){for(var k1 in args[k]){if(args[k][k1]){args[k1]=trx_addons_apply_filters('trx_addons_filter_prepare_global_param',args[k][k1],k1,clear);}}}else{args[k]=trx_addons_elm_prepare_global_params(args[k],clear);}}}
return args;};trx_addons_add_filter('trx_addons_filter_prepare_global_param',function(value,key,clear){var prefix='globals/colors?id=';if(value.indexOf(prefix)===0){if(clear){value='';}else{var id=value.replace(prefix,'');value='var(--e-global-color-'+id+')';}}
return value;});window.trx_addons_elm_restore_global_params=function(args){return trx_addons_elm_prepare_global_params(args,true);};})();