(function(blocks,i18n,element){"use strict";var el=element.createElement;trx_addons_add_filter('trx_addons_gb_map_get_params',function(atts,sc_gb){if(typeof TRX_ADDONS_SC_ADD_PARAMS=='object'){var sc=_trx_addons_sc_add_params_gb_to_sc_name(sc_gb.slice(-5)=='-item'?sc_gb.slice(0,-5):sc_gb);for(var i=0;i<TRX_ADDONS_SC_ADD_PARAMS.length;i++){var shortcode=TRX_ADDONS_SC_ADD_PARAMS[i];if(shortcode['sc'].indexOf(sc)!=-1&&_trx_addons_sc_add_params_check_builder('gutenberg',shortcode['builder'])){if(sc_gb.slice(-5)!='-item'&&(!shortcode.hasOwnProperty('inside')||!shortcode['inside'])||sc_gb.slice(-5)=='-item'&&shortcode.hasOwnProperty('inside')&&shortcode['inside']){atts=Object.assign(atts,_trx_addons_sc_add_params_get_gb_params(shortcode));}}}}
return atts;});function _trx_addons_sc_add_params_get_gb_params(shortcode){var gb_atts={};for(var param_name in shortcode['params']){var params=shortcode['params'][param_name];var param_type=_trx_addons_sc_add_params_get_gb_param_type(params);if(param_type===''){continue;}
var cur_atts={'type':param_type};if(params.hasOwnProperty('default')){cur_atts['default']=['checkbox','switch'].indexOf(params['type'])!=-1?!!params['default']:(['image','audio','video','media'].indexOf(params['type'])!=-1?0:params['default']);}else{cur_atts['default']=['checkbox','switch'].indexOf(params['type'])!=-1?false:'';}
gb_atts[param_name]=Object.assign({},cur_atts);if(['image','audio','video','media'].indexOf(params['type'])!=-1){gb_atts[param_name+'_url']={'type':'string','default':''};}}
return trx_addons_apply_filters('trx_addons_filter_sc_add_params_get_gb_params',gb_atts,shortcode);}
function _trx_addons_sc_add_params_get_gb_param_type(params){var gb_types=trx_addons_apply_filters('trx_addons_filter_gb_param_types',{'text':'string','textarea':'string','checkbox':'boolean','color':'string','image':'number','audio':'number','video':'number','media':'number','icon':'string','icons':'string','checklist':'string','switch':'boolean','number':'number','slider':'number','range':'number','url':'string','radio':'string','icons':'string','select':'string','heading':''});return trx_addons_apply_filters('trx_addons_filter_sc_add_params_get_gb_param_type',gb_types.hasOwnProperty(params['type'])?gb_types[params['type']]:params['type'],params);}
trx_addons_add_filter('trx_addons_gb_map_add_params',function(atts,sc_gb,props){var sc=_trx_addons_sc_add_params_gb_to_sc_name(sc_gb.slice(-5)=='-item'?sc_gb.slice(0,-5):sc_gb);for(var i=0;i<TRX_ADDONS_SC_ADD_PARAMS.length;i++){var shortcode=TRX_ADDONS_SC_ADD_PARAMS[i];if(shortcode['sc'].indexOf(sc)!=-1&&_trx_addons_sc_add_params_check_builder('gutenberg',shortcode['builder'])){if(sc_gb.slice(-5)!='-item'&&(!shortcode.hasOwnProperty('inside')||!shortcode['inside'])||sc_gb.slice(-5)=='-item'&&shortcode.hasOwnProperty('inside')&&shortcode['inside']){var pos=_trx_addons_sc_add_params_get_insert_point(atts,shortcode['before'],shortcode['after']);atts=[].concat(atts.slice(0,pos),_trx_addons_sc_add_params_get_gb_fields(shortcode),atts.slice(pos));}}}
return atts;});function _trx_addons_sc_add_params_get_gb_fields(shortcode){var gb_atts=[];for(var param_name in shortcode['params']){var params=shortcode['params'][param_name];var param_type=_trx_addons_sc_add_params_get_gb_field_type(params);if(param_type===''){continue;}
var cur_atts={'name':param_name,'type':param_type,'title':params.hasOwnProperty('title')?params['title']:'','descr':params.hasOwnProperty('description')?params['description']:'',};if(['image','audio','video','media'].indexOf(params['type'])!=-1){cur_atts['name_url']=param_name+'_url';}
if(params.hasOwnProperty('options')){cur_atts['options']=trx_addons_gutenberg_get_lists(params['options']);}else if(['icon','icons'].indexOf(params['type'])!=-1){cur_atts['options']=trx_addons_gutenberg_get_option_icons_classes();}
if(params.hasOwnProperty('min')){cur_atts['min']=params['min'];}
if(params.hasOwnProperty('max')){cur_atts['max']=params['max'];}
if(params.hasOwnProperty('step')){cur_atts['step']=params['step'];}
if(params.hasOwnProperty('mode')){cur_atts['mode']=params['mode'];}
if(params.hasOwnProperty('style')){cur_atts['style']=params['style'];}
if(params.hasOwnProperty('return')){cur_atts['return']=params['return'];}
if(params.hasOwnProperty('multiple')){cur_atts['multiple']=params['multiple'];}
if(params.hasOwnProperty('rows')){cur_atts['rows']=params['rows'];}
if(params.hasOwnProperty('dependency')&&typeof(params['dependency'])=='object'){cur_atts['dependency']=Object.assign({},params['dependency']);}
gb_atts.push(cur_atts);}
return trx_addons_apply_filters('trx_addons_filter_sc_add_params_add_gb_params',gb_atts,shortcode);}
function _trx_addons_sc_add_params_get_gb_field_type(params){var gb_types=trx_addons_apply_filters('trx_addons_filter_gb_field_types',{'text':'text','textarea':'textarea','checkbox':'boolean','color':'color','image':'image','audio':'text','video':'text','icon':'select','icons':'select','radio':'radio','select':'select','checklist':'select','switch':'boolean','number':'number','slider':'number','range':'number','url':'text','heading':''});return trx_addons_apply_filters('trx_addons_filter_sc_add_params_get_gb_field_type',gb_types.hasOwnProperty(params['type'])?gb_types[params['type']]:params['type'],params);}
function _trx_addons_sc_add_params_check_builder(builder,allowed){return allowed.indexOf(builder)!=-1||allowed.indexOf('all')!=-1;}
function _trx_addons_sc_add_params_gb_to_sc_name(gb_name){return trx_addons_apply_filters('trx_addons_filter_gb_to_sc_name',gb_name.replace('trx-addons/','trx_sc_').replace(/\-/g,'_'));}
function _trx_addons_sc_add_params_get_insert_point(atts,before,after){var i;for(i=0;i<atts.length;i++){if(before!==''&&atts[i]['name']==before){break;}else if(after!==''&&atts[i]['name']==after){i++;break;}}
return i;}})(window.wp.blocks,window.wp.i18n,window.wp.element);