;(function(window){'use strict';if(!window.Modernizr){return;}
var GalleryFxCollection={};var support={transitions:Modernizr.csstransitions},transEndEventNames={'WebkitTransition':'webkitTransitionEnd','MozTransition':'transitionend','OTransition':'oTransitionEnd','msTransition':'MSTransitionEnd','transition':'transitionend'},transEndEventName=transEndEventNames[Modernizr.prefixed('transition')],onEndTransition=function(el,callback){var onEndCallbackFn=function(e){if(support.transitions){if(e.target!=this){return;}
this.removeEventListener(transEndEventName,onEndCallbackFn);}
if(callback&&typeof callback==='function'){callback.call(this);}};if(support.transitions){el.addEventListener(transEndEventName,onEndCallbackFn);}else{onEndCallbackFn();}};function GalleryFx(el,options){this.galleryEl=el;this.options=extend({},this.options);extend(this.options,options);this.items=[].slice.call(this.galleryEl.querySelectorAll('.sc_portfolio_item'));if(jQuery(this.galleryEl).next('.sc_portfolio_preview').length===0){jQuery(this.galleryEl).after('<div class="sc_portfolio_preview'+(this.options.previewClass?' '+this.options.previewClass:'')+'">     <span class="sc_portfolio_preview_close trx_addons_button_close"><span class="sc_portfolio_preview_close_icon trx_addons_button_close_icon"></span></span>     <div class="sc_portfolio_preview_description"></div>    </div>');}
this.previewEl=nextSibling(this.galleryEl);this.isExpanded=false;this.isAnimating=false;this.closeCtrl=this.previewEl.querySelector('.sc_portfolio_preview_close');this.previewDescriptionEl=this.previewEl.querySelector('.sc_portfolio_preview_description');this._init();}
GalleryFx.prototype.options={pagemargin:0,imgPosition:{x:1,y:1},previewClass:'',onInit:function(instance){return false;},onResize:function(instance){return false;},onOpenItem:function(instance,item){return false;},onCloseItem:function(instance,item){return false;},onExpand:function(){return false;}};GalleryFx.prototype._init=function(){this.options.onInit(this);var self=this;trx_addons_when_images_loaded(jQuery(this.galleryEl),function(){self._initEvents();self._initMediaContainer();});};GalleryFx.prototype._initEvents=function(){var self=this;this.items.forEach(function(item){if(classie.has(item,'inited')){return;}
classie.add(item,'inited');var with_img=item.querySelector('img')||item.querySelector('.post_video')||item.querySelector('.post_featured');var disableClick=function(e){return(e.target.nodeName=='A'&&(!with_img||classie.has(e.target,'video_hover')&&e.target.closest('.sc_portfolio_item').getAttribute('data-details')))||(e.target.className||'').indexOf('video_frame_control_')!=-1||(e.target.className||'').indexOf('mejs')!=-1||(e.target.parentNode.className||'').indexOf('mejs')!=-1||(e.target.getAttribute('id')||'').indexOf('mejs')!=-1||(e.target.parentNode.getAttribute('id')||'').indexOf('mejs')!=-1;};item.addEventListener('click',function(e){if(disableClick(e)){return;}
e.preventDefault();self._openItem(e,item);});});this.closeCtrl.addEventListener('click',function(e){self._closeItem();e.preventDefault();return false;});window.addEventListener('resize',throttle(function(e){self.options.onResize(self);},10));};GalleryFx.prototype._initMediaContainer=function(){this.mediaContainer=document.createElement('div');this.mediaContainer.className='sc_portfolio_preview_media_container';this.mediaContainer.style.opacity=0;this.mediaContainer.style.maxWidth='calc('+parseInt(Math.abs(this.options.imgPosition.x)*100)+'vw - '+this.options.pagemargin+'px)';this.mediaContainer.style.maxHeight='calc('+parseInt(Math.abs(this.options.imgPosition.y)*100)+'vh - '+this.options.pagemargin+'px)';this.previewEl.appendChild(this.mediaContainer);this.styleTag=document.createElement('style');this.stylePrefix='sc_portfolio_preview_style_'+trx_addons_get_unique_id();this.previewEl.appendChild(this.styleTag);};GalleryFx.prototype._resetMediaContainer=function(){this.mediaContainer.style.opacity=0;this.mediaContainer.style.webkitTransform='translate3d(0,0,0) scale3d(1,1,1)';this.mediaContainer.style.transform='translate3d(0,0,0) scale3d(1,1,1)';this.mediaContainer.innerHTML='';};GalleryFx.prototype._setImage=function(src){var image=document.createElement('img');image.src=src;this.mediaContainer.appendChild(image);};GalleryFx.prototype._setVideo=function(video){this.mediaContainer.innerHTML=video;};GalleryFx.prototype._setStart=function(largeBounds,mediaBounds){var dx=mediaBounds.left-largeBounds.left,dy=mediaBounds.top-largeBounds.top,z=Math.min(mediaBounds.width / largeBounds.width,mediaBounds.height / largeBounds.height);this.styleTag.innerHTML='   @-webkit-keyframes sc-portfolio-show-media-container {    0%{     -webkit-transform: translate3d('+dx+'px,'+dy+'px,0) scale3d('+z+', '+z+',1);     transform: translate3d('+dx+'px,'+dy+'px,0) scale3d('+z+', '+z+',1);    }    100%{     -webkit-transform: translate3d(0,0,0) scale3d(1,1,1);     transform: translate3d(0,0,0) scale3d(1,1,1);    }   }   @keyframes sc-portfolio-show-media-container {    0%{     -webkit-transform: translate3d('+dx+'px,'+dy+'px,0) scale3d('+z+', '+z+',1);     transform: translate3d('+dx+'px,'+dy+'px,0) scale3d('+z+', '+z+',1);    }    100%{     -webkit-transform: translate3d(0,0,0) scale3d(1,1,1);     transform: translate3d(0,0,0) scale3d(1,1,1);    }   }  ';};GalleryFx.prototype._openItem=function(ev,item){var media=item.querySelector('.post_video');if(!media){media=item.querySelector('img');if(!media){media=item.querySelector('.post_featured');}}
if(this.isAnimating||this.isExpanded||!media){return;}
this.isAnimating=true;this.isExpanded=true;this.current=this.items.indexOf(item);var image=item.getAttribute('data-src'),video=item.getAttribute('data-video');if(video){this._setVideo(video);var player=jQuery(media).data('video-player');if(player&&typeof player.pauseVideo=='function'){player.pauseVideo();}}else{this._setImage(image);}
var self=this;trx_addons_when_images_loaded(jQuery(this.mediaContainer),function(){self.options.onOpenItem(self,item);var mediaBounds=media.getBoundingClientRect(),largeBounds=self.mediaContainer.getBoundingClientRect();self._setStart(largeBounds,mediaBounds);var description=item.getAttribute('data-details');if(description){self.previewDescriptionEl.innerHTML=description;}
setTimeout(function(){classie.add(self.previewEl,'sc_portfolio_preview_show');classie.add(self.mediaContainer,'sc_portfolio_preview_image_animate');self.mediaContainer.style.opacity=1;classie.add(item,'sc_portfolio_item_current');},0);var afterAnimationDone=false;function afterAnimation(){if(!afterAnimationDone){afterAnimationDone=true;classie.add(self.previewEl,'sc_portfolio_preview_image_loaded');classie.remove(self.mediaContainer,'sc_portfolio_preview_image_animate');self.isAnimating=false;self.options.onExpand();}}
onEndTransition(self.mediaContainer,afterAnimation);setTimeout(afterAnimation,1000);});};GalleryFx.prototype._closeItem=function(){if(!this.isExpanded||this.isAnimating){return;}
this.isExpanded=false;this.isAnimating=true;var galleryItem=this.items[this.current],galleryImg=galleryItem.querySelector('img')||galleryItem.querySelector('.post_featured'),galleryVideo=galleryItem.querySelector('.post_video'),galleryMedia=galleryVideo?galleryVideo:galleryImg,self=this;var mediaBounds=galleryMedia.getBoundingClientRect(),largeBounds=this.mediaContainer.getBoundingClientRect();classie.remove(this.previewEl,'sc_portfolio_preview_show');classie.remove(this.previewEl,'sc_portfolio_preview_image_loaded');this.options.onCloseItem(this,galleryItem);classie.add(this.mediaContainer,'sc_portfolio_preview_image_animate');setTimeout(function(){var dx=mediaBounds.left-largeBounds.left,dy=mediaBounds.top-largeBounds.top,z=Math.min(mediaBounds.width / largeBounds.width,mediaBounds.height / largeBounds.height);self.mediaContainer.style.webkitTransform='translate3d('+dx+'px, '+dy+'px, 0) scale3d('+z+', '+z+', 1)';self.mediaContainer.style.transform='translate3d('+dx+'px, '+dy+'px, 0) scale3d('+z+', '+z+', 1)';var afterAnimationDone=false;function afterAnimation(){if(!afterAnimationDone){afterAnimationDone=true;self.previewDescriptionEl.innerHTML='';classie.remove(galleryItem,'sc_portfolio_item_current');if(galleryVideo){var player=jQuery(galleryVideo).data('video-player');if(player&&typeof player.playVideo=='function'){player.playVideo();}}
setTimeout(function(){self.mediaContainer.style.opacity=0;},60);setTimeout(afterAnimation2,100);}
function afterAnimation2(){classie.remove(self.mediaContainer,'sc_portfolio_preview_image_animate');self._resetMediaContainer();self.isAnimating=false;}}
onEndTransition(self.mediaContainer,afterAnimation);setTimeout(afterAnimation,500);},10);};GalleryFx.prototype._getWinSize=function(){return{width:document.documentElement.clientWidth,height:window.innerHeight};};window.GalleryFx=GalleryFx;jQuery(document).on('action.init_hidden_elements',function(e,cont){if(cont===undefined)cont=jQuery('body');cont.find('.sc_portfolio_masonry_wrap:not(.preview_inited):not([data-gallery="0"]),.sc_portfolio_columns_wrap:not(.preview_inited):not([data-gallery="0"])').each(function(idx){if(jQuery(this).parents('div:hidden,article:hidden').length>0){return;}
var id=jQuery(this).addClass('preview_inited').attr('id');if(!id){id='gallery_fx_'+trx_addons_get_unique_id();jQuery(this).attr('id',id);}
GalleryFxCollection[id]=new GalleryFx(this,{previewClass:'scheme_dark',imgPosition:{x:-0.5,y:1},onOpenItem:function(instance,item){var animated=false;instance.items.forEach(function(el){if(item!=el&&!animated){if(!classie.has(el,'animated')){var delay=Math.floor(Math.random()*250);el.style.webkitTransition='opacity .5s '+delay+'ms cubic-bezier(.7,0,.3,1), -webkit-transform .5s '+delay+'ms cubic-bezier(.7,0,.3,1) !important';el.style.transition='opacity .5s '+delay+'ms cubic-bezier(.7,0,.3,1), transform .5s '+delay+'ms cubic-bezier(.7,0,.3,1) !important';el.style.webkitTransform='scale3d(0.1,0.1,1) !important';el.style.transform='scale3d(0.1,0.1,1) !important';el.style.opacity='0 !important';}else{animated=true;}}});},onCloseItem:function(instance,item){var animated=false;instance.items.forEach(function(el){if(item!=el&&!animated){if(!classie.has(el,'animated')){el.style.webkitTransition='opacity .4s, -webkit-transform .4s !important';el.style.transition='opacity .4s, transform .4s !important';el.style.webkitTransform='scale3d(1,1,1) !important';el.style.transform='scale3d(1,1,1) !important';el.style.opacity='1 !important';setTimeout(function(){el.style.webkitTransition='none';el.style.transition='none';el.style.webkitTransform='none';el.style.transform='none';},500);}else{animated=true;}}});},onExpand:function(){var content=jQuery('.sc_portfolio_preview');if(content.length>0){content.find('.inited').removeClass('inited');jQuery(document).trigger('action.init_hidden_elements',[content]);jQuery(window).trigger('resize');}}});});});function throttle(fn,delay){var allowSample=true;return function(e){if(allowSample){allowSample=false;setTimeout(function(){allowSample=true;},delay);fn(e);}};}
function nextSibling(el){var nextSibling=el.nextSibling;while(nextSibling&&nextSibling.nodeType!=1){nextSibling=nextSibling.nextSibling;}
return nextSibling;}
function extend(a,b){for(var key in b){if(b.hasOwnProperty(key)){a[key]=b[key];}}
return a;}})(window);