jQuery(document).ready(function(){"use strict";if(typeof window.elementorFrontend!=='undefined'&&elementorFrontend.isEditMode()){return;}
var requestAnimationFrame=trx_addons_request_animation_frame();var _sounds={},_playing_max=2,_playing_saved=-1,_playing=_playing_max,_playing_bg_url_saved=trx_addons_get_cookie('trx_addons_audio_effects_playing_url'),_playing_bg_id='',_playing_bg_id_next='',_playing_bg_time=0;var id='',idx=0,data,items;var _playing_3rd_party_audio=false;var $window=jQuery(window),$document=jQuery(document),$body=jQuery('body'),$audio_effects=jQuery('.sc_audio_effects');if($audio_effects.length>0){_playing_saved=trx_addons_get_cookie('trx_addons_audio_effects_playing',-1);if(_playing_saved!==-1){_playing=parseInt(_playing_saved,10);}}
if(typeof TRX_ADDONS_STORAGE=='undefined'||typeof TRX_ADDONS_STORAGE['audio_effects_allowed']=='undefined'||TRX_ADDONS_STORAGE['audio_effects_allowed']!=1||typeof window.Howl=='undefined'){init_indicator();return;}
$document.on('action.got_ajax_response',update_jquery_links);$document.on('action.init_hidden_elements',update_jquery_links);var first_run=true;function update_jquery_links(e){if(first_run&&e&&e.namespace=='init_hidden_elements'){first_run=false;return;}
jQuery('.trx_addons_audio_effects_on:not(.audio_effects_inited)').each(function(){var $self=jQuery(this).addClass('audio_effects_inited'),data=$self.data('trx-addons-audio-effects'),id='';if(typeof data=='object'){var $items;for(var i in data){$items=data[i].selectors!==''?$self.find(data[i].selectors):$self;if($items.length>0){id=add_sound(data[i],'sc_');if(id){init_event_handler(id,$self);}}}}});jQuery('audio:not(.audio_effects_listeners_inited)').each(function(){var media=jQuery(this).addClass('audio_effects_listeners_inited').get(0);media.addEventListener('play',function(){_playing_3rd_party_audio=true;sound_stop('page_load');page_background(false);});media.addEventListener('pause',function(){_playing_3rd_party_audio=false;page_background(true);});media.addEventListener('ended',function(){_playing_3rd_party_audio=false;page_background(true);});});}
if(typeof TRX_ADDONS_STORAGE['audio_effects_allowed']!='undefined'&&TRX_ADDONS_STORAGE['audio_effects_allowed']==1&&typeof TRX_ADDONS_STORAGE['audio_effects']!='undefined'){for(var i=0;i<TRX_ADDONS_STORAGE['audio_effects'].length;i++){data=TRX_ADDONS_STORAGE['audio_effects'][i];id=add_sound(data,'page_');if(id&&data.selectors&&['click','hover'].indexOf(data.event)!=-1){items=jQuery(data.selectors);if(items.length>0){init_event_handler(id,items);}}}}
update_jquery_links();if(idx===0){_playing=0;}else if(_playing_bg_id===''){_playing_max=1;_playing=Math.min(_playing,_playing_max);}else{_playing_bg_id_next=get_next_background(_playing_bg_id);}
init_indicator();if(_sounds.hasOwnProperty('page_load')&&_sounds['page_load'].url!==''){page_load();}else{page_background(true);}
function page_load(){if(_sounds.hasOwnProperty('page_load')&&_sounds['page_load'].url!==''&&_playing>0&&!_playing_3rd_party_audio){sound_play('page_load');}}
function page_background(play){if(_playing_bg_id){if(play){if(_playing>1&&!_playing_3rd_party_audio){var time=0;if(_sounds[_playing_bg_id].state===''){time=trx_addons_get_cookie('trx_addons_audio_effects_playing_time',0);if(time>0){if(_sounds[_playing_bg_id].url.substring(_sounds[_playing_bg_id].url.lastIndexOf('/')+1)!=trx_addons_get_cookie('trx_addons_audio_effects_playing_url')){time=0;}}else{time=0;}}
sound_play(_playing_bg_id,time);}}else{sound_pause(_playing_bg_id);}}}
function get_next_background(id){var id_next='',i,start=false;for(i in _sounds){if(i==id){start=true;}else if(start&&_sounds[i].event=='background'){id_next=i;break;}}
if(id_next===''){start=true;for(i in _sounds){if(i==id){break;}else if(_sounds[i].event=='background'){id_next=i;break;}}}
return id_next;}
function preload_next_background(){if(_playing_bg_id){_playing_bg_time=_sounds[_playing_bg_id].howl.seek();if(_playing_bg_id_next&&_playing_bg_id!=_playing_bg_id_next&&_sounds[_playing_bg_id_next].state===''){var duration=_sounds[_playing_bg_id].howl.duration();if(!duration||duration-_playing_bg_time<30){_sounds[_playing_bg_id_next].state='loading';sound_load(_playing_bg_id_next);}}
setTimeout(preload_next_background,500);}}
$window.on('unload',function(){trx_addons_set_cookie('trx_addons_audio_effects_playing_time',_playing_bg_time);trx_addons_set_cookie('trx_addons_audio_effects_playing_url',_playing_bg_id?_sounds[_playing_bg_id].url.substring(_sounds[_playing_bg_id].url.lastIndexOf('/')+1):'');});function init_event_handler(id,items){items.each(function(){var $self=jQuery(this),ae_class=_sounds[id].event+'_inited',event=_sounds[id].event.replace('hover','mouseenter')+'.trx_addons_audio_effects';if($self.hasClass(ae_class)){$self.off(event);}
$self.toggleClass(ae_class,true).on(event,get_event_handler(event,id,function(id){if(_playing>0){sound_play(id);}}));});}
function get_event_handler(event,id,cb){return function(e){cb(id);};}
function get_event_callbacks(event){if(event=='load'){return{onend:function(){page_background(true);}};}else if(event=='background'){return{onplay:function(){setTimeout(preload_next_background,500);},onend:function(){if(_playing_bg_id_next&&_playing_bg_id!=_playing_bg_id_next){sound_stop(_playing_bg_id);_playing_bg_id=_playing_bg_id_next;_playing_bg_id_next=get_next_background(_playing_bg_id);page_background(true);}}};}}
function add_sound(data,prefix){var local=data.hasOwnProperty('local')?(typeof data.local=='object'?data.local.url:data.local):'',url=local!==''?local:data.link,id='';if(url){id=prefix+data.event+('load'!=data.event?'_'+idx:'');idx++;_sounds[id]={event:data.event,selectors:data.hasOwnProperty('selectors')?data.selectors:'',state:'',howl:null,sound_id:null,loop:data.hasOwnProperty('loop')?data.loop:'background'==data.event,preload:data.hasOwnProperty('preload')?data.preload:'background'!=data.event||_playing_bg_id==='',url:url,volume:Math.max(0,Math.min(100,typeof data.volume=='object'?data.volume.size:data.volume))/ 100,callbacks:get_event_callbacks(data.event)};if(data.event=='background'){if(_playing_bg_id===''||(_playing_bg_url_saved&&url.substring(url.lastIndexOf('/')+1)==_playing_bg_url_saved)){if(_playing_bg_id!==''){_sounds[_playing_bg_id].preload=false;}
_playing_bg_id=id;_sounds[_playing_bg_id].preload=true;}}}
return id;}
function sound_play(id,time){if(_sounds.hasOwnProperty(id)&&_sounds[id].url!==''){var howl=sound_get(id);if(howl){if(true||_sounds[id].state!==''){if(false&&_sounds[id].sound_id&&_sounds[id].state=='playing'){howl.stop(_sounds[id].sound_id);_sounds[id].sound_id=null;}
_sounds[id].sound_id=howl.play();if(time>0&&_sounds[id].sound_id){howl.seek(time,_sounds[id].sound_id);}}else{howl.once('load',function(){_sounds[id].sound_id=howl.play();});}}}}
function sound_pause(id){if(_sounds.hasOwnProperty(id)&&_sounds[id].howl){_sounds[id].howl.pause();}}
function sound_stop(id){if(_sounds.hasOwnProperty(id)&&_sounds[id].howl){_sounds[id].howl.stop();}}
function sound_load(id){if(_sounds.hasOwnProperty(id)&&_sounds[id].url!==''){var howl=sound_get(id);if(howl){howl.load();}}}
function sound_get(id){var howl=false,cb={};if(_sounds.hasOwnProperty(id)&&_sounds[id].url!==''){if(!_sounds[id].howl){if(_sounds[id].callbacks){cb=_sounds[id].callbacks;}
howl=_sounds[id].howl=new Howl({src:[_sounds[id].url],preload:_sounds[id].preload,loop:_sounds[id].loop,volume:_sounds[id].volume,onplayerror:function(sound_id,error){},onplay:function(sound_id){_sounds[id].state='playing';if(cb.hasOwnProperty('onplay')){cb.onplay(_sounds[id],sound_id);}},onload:function(sound_id){if(_sounds[id].state===''||_sounds[id].state==='loading'){_sounds[id].state='loaded';}
if(cb.hasOwnProperty('onload')){cb.onload(_sounds[id],sound_id);}},onend:function(sound_id){_sounds[id].state='finished';if(cb.hasOwnProperty('onend')){cb.onend(_sounds[id],sound_id);}},onpause:function(sound_id){_sounds[id].state='paused';if(cb.hasOwnProperty('onpause')){cb.onpause(_sounds[id],sound_id);}},onstop:function(sound_id){_sounds[id].state='stopped';if(cb.hasOwnProperty('onstop')){cb.onstop(_sounds[id],sound_id);}},onseek:function(sound_id){if(cb.hasOwnProperty('onseek')){cb.onseek(_sounds[id],sound_id);}}});}else{howl=_sounds[id].howl;}}
return howl;}
function init_indicator(){$audio_effects.each(function(){jQuery(this).addClass('audio_effects_inited sc_audio_effects_'+(idx===0||_playing===0?'off':(_playing==1?'events':'on'))).on('click',function(e){if(idx>0){_playing=(_playing+1)%(_playing_max+1);trx_addons_set_cookie('trx_addons_audio_effects_playing',_playing);$audio_effects.removeClass('sc_audio_effects_on sc_audio_effects_off sc_audio_effects_events').addClass('sc_audio_effects_'+(_playing===0?'off':(_playing==1?'events':'on')));page_background(_playing>1);}
e.preventDefault();return false;});});}});