jQuery(document).ready(function(){"use strict";var $window=jQuery(window),$document=jQuery(document),$body=jQuery('body');window.trx_addons_ai_helper_agenerator_load_audio=function($tag){$tag.parents('.sc_agenerator_audio_inner').removeClass('sc_agenerator_audio_loading');};window.trx_addons_ai_helper_agenerator_reload_audio=function($tag){if(($tag.data('total-reloads')||0)<20&&$tag.attr('src')!==''&&trx_addons_is_external_url($tag.attr('src'))){$tag.data('total-reloads',($tag.data('total-reloads')||0)+1).parents('.sc_agenerator_audio_inner').addClass('sc_agenerator_audio_loading');var src=$tag.attr('src');setTimeout(function(){$tag.attr('src','');$tag.attr('src',src);},5000);}};$document.on('action.init_hidden_elements',function(e,container){if(container===undefined){container=$body;}
var animation_out=trx_addons_apply_filters('trx_addons_filter_sc_agenerator_animation_out','fadeOutDownSmall animated normal'),animation_in=trx_addons_apply_filters('trx_addons_filter_sc_agenerator_animation_in','fadeInUpSmall animated normal');container.find('.sc_agenerator:not(.sc_agenerator_inited)').each(function(){var $sc=jQuery(this).addClass('sc_agenerator_inited'),$form=$sc.find('.sc_agenerator_form'),$prompt=$sc.find('.sc_agenerator_form_field_prompt_text'),$upload_audio=$sc.find('.sc_agenerator_form_field_upload_audio_field'),$button=$sc.find('.sc_agenerator_form_field_generate_button'),$settings=$sc.find('.sc_agenerator_form_settings'),$settings_button=$sc.find('.sc_agenerator_form_settings_button'),$model=$sc.find('[name="sc_agenerator_form_field_model"]'),$language=$sc.find('[name="sc_agenerator_form_field_language"]'),$emotion=$sc.find('[name="sc_agenerator_form_field_emotion"]'),$voice_openai=$sc.find('[name="sc_agenerator_form_field_voice_openai"]'),$voice_modelslab=$sc.find('[name="sc_agenerator_form_field_voice_modelslab"]'),$upload_voice_modelslab=$sc.find('.sc_agenerator_form_field_upload_voice_modelslab_field'),$preview=$sc.find('.sc_agenerator_audio'),$actions=$sc.find('.sc_agenerator_form_actions'),$actions_slider=$sc.find('.sc_agenerator_form_actions_slider:not(.sc_agenerator_form_actions_slider_inited)').addClass('sc_agenerator_form_actions_slider_inited');var need_resize=trx_addons_apply_filters('sc_agenerator_filter_need_resize',$sc.parents('.sc_switcher').length>0),resize_delay=trx_addons_apply_filters('sc_agenerator_filter_resize_delay',animation_in||animation_out?400:0);$settings_button.on('click',function(e){e.preventDefault();if($settings.find('.sc_agenerator_form_settings_field:not(.trx_addons_hidden)').length>0){$settings.toggleClass('sc_agenerator_form_settings_show');}
return false;});$document.on('click',function(e){if($settings.hasClass('sc_agenerator_form_settings_show')&&!jQuery(e.target).closest('.sc_agenerator_form_settings').length){$settings.removeClass('sc_agenerator_form_settings_show');}});$model.on('change',function(){check_fields_visibility();});$prompt.on('change keyup',function(){check_fields_visibility();});$upload_audio.on('change',function(){check_fields_visibility();});$sc.find('.sc_agenerator_form_settings_field_numeric_wrap_button_inc,.sc_agenerator_form_settings_field_numeric_wrap_button_dec,.sc_agenerator_form_field_numeric_wrap_button_inc,.sc_agenerator_form_field_numeric_wrap_button_dec').on('click',function(e){e.preventDefault();var $self=jQuery(this),$field=$self.parents('.sc_agenerator_form_settings_field_numeric_wrap,.sc_agenerator_form_field_numeric_wrap').eq(0),$input=$field.find('input'),val=Number($input.val()||0),step=Number($input.attr('step')||1),min=Number($input.attr('min')||0),max=Number($input.attr('max')||1024);if($self.hasClass('sc_agenerator_form_settings_field_numeric_wrap_button_inc')||$self.hasClass('sc_agenerator_form_field_numeric_wrap_button_inc')){val=Math.min(max,val+step);}else{val=Math.max(min,val-step);}
if(step<0.1){val=Math.round(val*100)/ 100;}else if(step<1){val=Math.round(val*10)/ 10;}
$input.val(val).trigger('change');return false;});$upload_audio.on('change',function(e){var $self=jQuery(this),file=$self.val().replace(/\\/g,'/').replace(/.*\//,'');$self.parent().toggleClass('filled',true).find('.sc_agenerator_form_field_upload_audio_text').removeClass('theme_form_field_placeholder').text(file);});$upload_voice_modelslab.on('change',function(e){var $self=jQuery(this),file=$self.val().replace(/\\/g,'/').replace(/.*\//,'');$self.parent().toggleClass('filled',true).find('.sc_agenerator_form_field_upload_voice_modelslab_text').removeClass('theme_form_field_placeholder').text(file);});$sc.on('click','.sc_agenerator_message_close',function(e){e.preventDefault();$form.find('.sc_agenerator_message').slideUp();return false;});$prompt.on('keydown',function(e){if(e.keyCode==13){e.preventDefault();$button.trigger('click');return false;}});$actions.on('click','a[data-action]',function(e){e.preventDefault();var $self=jQuery(this),$item=$self.parent();if(!$item.hasClass('sc_agenerator_form_actions_item_active')){$item.siblings('.sc_agenerator_form_actions_item_active').removeClass('sc_agenerator_form_actions_item_active');$item.addClass('sc_agenerator_form_actions_item_active');trx_addons_ai_helper_agenerator_move_slider_to_active_item();change_models($self.data('action'));check_fields_visibility();}
return false;});window.trx_addons_ai_helper_agenerator_move_slider_to_active_item=function(){var $active=$actions.find('.sc_agenerator_form_actions_item_active a');if($active.length){$actions_slider.css({left:$active.offset().left-$actions.offset().left,width:$active.outerWidth()});}};trx_addons_ai_helper_agenerator_move_slider_to_active_item();$document.on('action.resize_trx_addons',trx_addons_debounce(trx_addons_ai_helper_agenerator_move_slider_to_active_item,200));function change_models(action){var models=$model.data('models')||'';if(models[action]){var output='';var group=false;for(var model in models[action]){if(model.slice(-2)=='/-'||models[action][model].slice(0,2)=='\\-'){if(group){output+='</optgroup>';}
group=true;output+='<optgroup label="'+models[action][model].slice(2)+'">';}else{output+='<option value="'+model+'">'+models[action][model]+'</option>';}}
if(group){output+='</optgroup>';}
$model.html(output);}}
function check_fields_visibility(){var action=$actions.find('.sc_agenerator_form_actions_item_active a').data('action');var model=($model.is('input[type="radio"]')?$model.filter(':checked').val():$model.val())||'';var disabled=false;if(action=='tts'){disabled=$prompt.attr('disabled')=='disabled'||$prompt.val()=='';}else if(action!=='tts'){disabled=$upload_audio.attr('disabled')=='disabled'||$upload_audio.val()=='';}
$button.toggleClass('sc_agenerator_form_field_prompt_button_disabled sc_agenerator_form_field_disabled',disabled);$form.find('.sc_agenerator_form_field,.sc_agenerator_form_settings_field').each(function(){var $self=jQuery(this),actions=$self.data('actions'),visible=!actions||actions.indexOf(action)>=0;if($self.data('models')){var parts=$self.data('models').split(','),allow=false;for(var i=0;i<parts.length;i++){if(model.indexOf(parts[i])>=0){allow=true;break;}}
visible&&=allow;}
if($self.attr('class').indexOf('upload_audio')>0){visible&&=!(model.indexOf('openai/')>=0&&action=='tts');}
need_resize|=(visible&&$self.hasClass('trx_addons_hidden'))||(!visible&&!$self.hasClass('trx_addons_hidden'));$self.toggleClass('trx_addons_hidden',!visible);});if($settings.find('.sc_agenerator_form_settings_field:not(.trx_addons_hidden)').length==0){$settings_button.attr('disabled','disabled');}else{$settings_button.removeAttr('disabled');}
if(need_resize){$document.trigger('action.resize_trx_addons');}}
check_fields_visibility();$button.on('click',function(e){e.preventDefault();var action_type=$actions.find('.sc_agenerator_form_actions_item_active a').data('action'),model=$model.val(),prompt='',settings=$form.data('agenerator-settings'),form_type='data',error_msg='';if(!check_limits()){return false;}
$form.addClass('sc_agenerator_form_loading');var data={nonce:TRX_ADDONS_STORAGE['ajax_nonce'],action:'trx_addons_ai_helper_agenerator',action_type:action_type,settings:settings,model:model,count:(trx_addons_get_cookie('trx_addons_ai_helper_agenerator_count')||0)*1+1};if(action_type=='tts'){prompt=data.prompt=$prompt.val()||'';}
if($upload_audio.length&&$upload_audio.val()&&(action_type!='tts'||data.model.indexOf('modelslab/')>=0)){data.upload_audio={file:$upload_audio.get(0).files[0],name:$upload_audio.get(0).files[0].name};form_type='file';}
if(action_type=='tts'||(action_type=='voice-cover'&&data.model.indexOf('modelslab/')>=0)){data.voice=data.model.indexOf('openai/')>=0?$form.find('select[name="sc_agenerator_form_field_voice_openai"]').val()||'':(action_type=='tts'?$form.find('input[name="sc_agenerator_form_field_voice_modelslab"]').val()||'':$form.find('input[name="sc_agenerator_form_field_voice_cloning_modelslab"]').val()||'');}
if((action_type=='tts'||action_type=='voice-cover')&&data.model.indexOf('modelslab/')>=0){if($upload_voice_modelslab.length&&$upload_voice_modelslab.val()){data.upload_voice={file:$upload_voice_modelslab.get(0).files[0],name:$upload_voice_modelslab.get(0).files[0].name};form_type='file';}}
if(['tts','transcription','voice-cover'].indexOf(action_type)>=0&&data.model.indexOf('modelslab/')>=0){data.language=$form.find('select[name="sc_agenerator_form_field_language"]').val()||'english';}
if(['tts','voice-cover'].indexOf(action_type)>=0&&data.model.indexOf('modelslab/')>=0){data.emotion=$form.find('select[name="sc_agenerator_form_field_emotion"]').val()||'neutral';}
if(action_type=='tts'&&data.model.indexOf('openai/')>=0){data.speed=$form.find('input[name="sc_agenerator_form_settings_field_speed"]').val()||1;}
if(['translation','transcription'].indexOf(action_type)>=0&&data.model.indexOf('openai/')>=0){data.temperature=$form.find('input[name="sc_agenerator_form_settings_field_temperature"]').val()||0;}
if(action_type=='voice-cover'&&data.model.indexOf('modelslab/')>=0){data.rate=$form.find('input[name="sc_agenerator_form_settings_field_rate"]').val()||0.5;data.radius=$form.find('input[name="sc_agenerator_form_settings_field_radius"]').val()||3;data.originality=$form.find('input[name="sc_agenerator_form_settings_field_originality"]').val()||0.33;}
if(form_type=='file'){var formData=new FormData();for(var key in data){if(typeof data[key]=='object'&&data[key].file){formData.append(key,data[key].file,data[key].name);}else{formData.append(key,data[key]);}}
jQuery.ajax({url:TRX_ADDONS_STORAGE['ajax_url'],type:"POST",data:formData,processData:false,contentType:false,success:['tts','voice-cover'].indexOf(action_type)>=0?getAudio:getResponse});}else{jQuery.post(TRX_ADDONS_STORAGE['ajax_url'],data,['tts','voice-cover'].indexOf(action_type)>=0?getAudio:getResponse);}
function getAudio(response){var rez=trx_addons_parse_ajax_response(response,TRX_ADDONS_STORAGE['msg_ai_helper_error']);$form.removeClass('sc_agenerator_form_loading');if(!rez.error&&rez.data){var i=0;if(rez.data.fetch_id){for(i=0;i<rez.data.fetch_number;i++){rez.data.audio.push({url:rez.data.fetch_audio});}
var time=rez.data.fetch_time?rez.data.fetch_time:8000;setTimeout(function(){fetch_data(rez.data);},time);}
if(rez.data.audio.length>0){if(!rez.data.demo){update_limits_counter(rez.data.audio.length);update_requests_counter();}
var $audio=$preview.find('.sc_agenerator_audio_item');if(animation_in||animation_out){$preview.css({'height':$audio.length?$preview.height()+'px':'12em',});}
if(!$audio.length){$preview.show();}else if(animation_out){$audio.removeClass(animation_in).addClass(animation_out);}
setTimeout(function(){var currentDate=new Date();var timestamp=currentDate.getTime();var icon=$form.data('agenerator-download-icon')||'trx_addons_icon-download';var html='<div class="sc_agenerator_audio_item_wrap">';for(var i=0;i<rez.data.audio.length;i++){html+='<div class="sc_agenerator_audio_item'
+(rez.data.fetch_id?' sc_agenerator_audio_fetch':'')
+(animation_in?' '+animation_in:'')
+'">'
+'<div class="sc_agenerator_audio_inner">'
+'<div class="sc_agenerator_audio_wrap">'
+'<audio controls="controls" preload="metadata"'
+(rez.data.fetch_id?' id="fetch-'+rez.data.fetch_id+'"':' src="'+rez.data.audio[i].url+'"')
+'></audio>'
+(rez.data.fetch_id?'<span class="sc_agenerator_audio_fetch_info">'
+'<span class="sc_agenerator_audio_fetch_progress">'
+'<span class="sc_agenerator_audio_fetch_progressbar"></span>'
+'</span>'
+'<span class="sc_agenerator_audio_fetch_msg">'+rez.data.fetch_msg+'</span>'
+'</span>':'')
+'</div>'
+(!rez.data.demo&&rez.data.show_download?'<a href="'+get_download_link(rez.data.audio[i].url?rez.data.audio[i].url:'#')+'"'
+' download="'+prompt.replace(/[\s]+/g,'-').toLowerCase()+'"'
+' data-expired="'+((rez.data.fetch_id?0:timestamp)+rez.data.show_download*1000)+'"'
+' class="sc_agenerator_audio_link sc_button sc_button_default sc_button_size_small sc_button_with_icon sc_button_icon_left"'
+'>'
+(icon&&!trx_addons_is_off(icon)?'<span class="sc_button_icon"><span class="'+icon+'"></span></span>':'')
+'<span class="sc_button_text"><span class="sc_button_title">'+TRX_ADDONS_STORAGE['msg_ai_helper_agenerator_download']+'</span></span>'
+'</a>':'')
+'</div>'
+'</div>';}
html+='</div>';$preview.html(html);$preview.find('.sc_agenerator_audio_inner audio').on('load',function(){trx_addons_ai_helper_agenerator_load_audio(jQuery(this));}).on('error',function(){trx_addons_ai_helper_agenerator_reload_audio(jQuery(this));});$preview.css('height','auto');$sc.addClass('sc_agenerator_audio_show');if(!rez.data.fetch_id){$document.trigger('action.init_hidden_elements',[$preview]);}
if(need_resize){setTimeout(function(){$document.trigger('action.resize_trx_addons');},resize_delay);}
$preview.find('.sc_agenerator_audio_link').on('click',function(e){var currentDate=new Date();var timestamp=currentDate.getTime();var $link=jQuery(this);if($link.attr('data-expired')&&parseInt($link.attr('data-expired'),10)<timestamp){e.preventDefault();if(typeof trx_addons_msgbox_warning=='function'){trx_addons_msgbox_warning(TRX_ADDONS_STORAGE['msg_ai_helper_agenerator_download_expired'],TRX_ADDONS_STORAGE['msg_ai_helper_agenerator_download_error'],'attention',0,[TRX_ADDONS_STORAGE['msg_caption_ok']]);}else{show_message(TRX_ADDONS_STORAGE['msg_ai_helper_agenerator_download_expired'],'error');}
return false;}});},$audio.length&&animation_out?700:0);}
if(rez.data.message){show_message(rez.data.message,rez.data.message_type);}}else{if(typeof trx_addons_msgbox_warning=='function'){trx_addons_msgbox_warning(rez.error,TRX_ADDONS_STORAGE['msg_ai_helper_agenerator_download_error'],'attention',0,[TRX_ADDONS_STORAGE['msg_caption_ok']]);}else{show_message(rez.error,'error');}}}
function getResponse(response){var rez=trx_addons_parse_ajax_response(response,TRX_ADDONS_STORAGE['msg_ai_helper_error']);$form.removeClass('sc_agenerator_form_loading');if(!rez.error&&rez.data){if(rez.data.text){var $text=$preview.find('.sc_agenerator_text_wrap');$preview.show();if(animation_in||animation_out){$preview.css({'height':$preview.height()+'px'});}
if(animation_out){$text.removeClass(animation_in).addClass(animation_out);}
setTimeout(function(){$preview.html('<div class="sc_agenerator_text_wrap">'
+'<textarea class="sc_agenerator_text">'
+rez.data.text
+'</textarea>'
+'</div>');$preview.css('height','auto');$sc.addClass('sc_agenerator_audio_show');if(need_resize){setTimeout(function(){$document.trigger('action.resize_trx_addons');},resize_delay);}},animation_out?700:0);}
if(rez.data.message){show_message(rez.data.message,rez.data.message_type);}}else{if(typeof trx_addons_msgbox_warning=='function'){trx_addons_msgbox_warning(rez.error,TRX_ADDONS_STORAGE['msg_ai_helper_agenerator_download_error'],'attention',0,[TRX_ADDONS_STORAGE['msg_caption_ok']]);}else{show_message(rez.error,'error');}}}});function fetch_data(data){jQuery.post(TRX_ADDONS_STORAGE['ajax_url'],{nonce:TRX_ADDONS_STORAGE['ajax_nonce'],action:'trx_addons_ai_helper_fetch_audio',fetch_id:data.fetch_id,fetch_url:data.fetch_url,},function(response){var rez=trx_addons_parse_ajax_response(response,TRX_ADDONS_STORAGE['msg_ai_helper_error']);if(!rez.error){if(rez.data&&rez.data.audio&&rez.data.audio.length>0){var audio=rez.data.audio,$fetch=$preview.find('#fetch-'+data.fetch_id);if($fetch.length){var $download_link;var currentDate=new Date();var timestamp=currentDate.getTime();var $audio;for(var i=0;i<audio.length;i++){if($fetch.eq(i).is('audio')){$audio=$fetch.eq(i);}else{$audio=$fetch.eq(i).find('audio');}
$audio.attr('src',audio[i].url).parents('.sc_agenerator_audio_fetch').removeClass('sc_agenerator_audio_fetch').find('.sc_agenerator_audio_fetch_info').remove();$download_link=$fetch.eq(i).parents('.sc_agenerator_audio_item').find('.sc_agenerator_audio_link');$download_link.attr('href',get_download_link(audio[i].url));$download_link.attr('data-expired',parseInt($download_link.attr('data-expired'),10)+timestamp);$document.trigger('action.init_hidden_elements',[$preview]);}}else{$preview.empty();show_message(TRX_ADDONS_STORAGE['msg_ai_helper_agenerator_fetch_error'],'error');}}else{setTimeout(function(){fetch_data(data);},data.fetch_time?data.fetch_time:8000);}}else{$preview.empty();show_message(rez.error,'error');}});}
function show_message(msg,type){if(msg.indexOf('<p>')==-1){msg='<p>'+msg+'</p>';}
$form.find('.sc_agenerator_message_inner').html(msg).parent().toggleClass('sc_agenerator_message_type_error',type=='error').toggleClass('sc_agenerator_message_type_info',type=='info').toggleClass('sc_agenerator_message_type_success',type=='success').addClass('sc_agenerator_message_show').slideDown(function(){if(need_resize){$document.trigger('action.resize_trx_addons');}});}
function check_limits(){if(!$form.data('agenerator-demo-audio')){var total,used,number;var $limit_total=$form.find('.sc_agenerator_limits_total_value'),$limit_used=$form.find('.sc_agenerator_limits_used_value');if($limit_total.length&&$limit_used.length){total=parseInt($limit_total.text(),10);used=parseInt($limit_used.text(),10);number=parseInt($form.data('agenerator-number'),10);if(!isNaN(total)&&!isNaN(used)&&!isNaN(number)){if(used>=total){disable_fields();return false;}}}
var $requests_total=$form.find('.sc_agenerator_limits_total_requests'),$requests_used=$form.find('.sc_agenerator_limits_used_requests');if($requests_total.length&&$requests_used.length){total=parseInt($requests_total.text(),10);used=(trx_addons_get_cookie('trx_addons_ai_helper_agenerator_count')||0)*1;if(!isNaN(total)&&!isNaN(used)){if(used>=total){disable_fields();return false;}}}}
return true;}
function disable_fields(){$button.toggleClass('sc_agenerator_form_field_prompt_button_disabled sc_agenerator_form_field_disabled',true);$prompt.attr('disabled','disabled');$upload_audio.attr('disabled','disabled');$model.attr('disabled','disabled');$voice_openai.attr('disabled','disabled');$voice_modelslab.attr('disabled','disabled');$language.attr('disabled','disabled');$emotion.attr('disabled','disabled');show_message($form.data('agenerator-limit-exceed'),'error');}
function update_limits_counter(number){var total,used;var $limit_total=$form.find('.sc_agenerator_limits_total_value'),$limit_used=$form.find('.sc_agenerator_limits_used_value');if($limit_total.length&&$limit_used.length){total=parseInt($limit_total.text(),10);used=parseInt($limit_used.text(),10);if(!isNaN(total)&&!isNaN(used)&&!isNaN(number)){if(used<total){used=Math.min(used+number,total);$limit_used.text(used);}}}
var $requests_total=$form.find('.sc_agenerator_limits_total_requests'),$requests_used=$form.find('.sc_agenerator_limits_used_requests');if($requests_total.length&&$requests_used.length){total=parseInt($requests_total.text(),10);used=(trx_addons_get_cookie('trx_addons_ai_helper_agenerator_count')||0)*1;if(!isNaN(total)&&!isNaN(used)){if(used<total){used=Math.min(used+1,total);$requests_used.text(used);}}}}
function update_requests_counter(){var count=trx_addons_get_cookie('trx_addons_ai_helper_agenerator_count')||0,limit=60*60*1000*1,expired=limit-(new Date().getTime()%limit);trx_addons_set_cookie('trx_addons_ai_helper_agenerator_count',++count,expired);}
function get_download_link(url){return url;}});});});