'use strict';function Curtains(params){this.planes=[];this.renderTargets=[];this.shaderPasses=[];this._imageCache=[];this._drawStacks={"opaque":{length:0,programs:[],order:[],},"transparent":{length:0,programs:[],order:[],},"renderPasses":[],"scenePasses":[],};this._drawingEnabled=true;this._forceRender=false;if(typeof params==="string"){console.warn("Since v4.0 you should use an object to pass your container and other parameters. Please refer to the docs: https://www.curtainsjs.com/documentation.html");var container=params;params={container:container};}
if(!params.container){var container=document.createElement("div");container.setAttribute("id","curtains-canvas");document.body.appendChild(container);this.container=container;}
else{if(typeof params.container==="string"){this.container=document.getElementById(params.container);}
else if(params.container instanceof Element){this.container=params.container;}}
this._autoResize=params.autoResize;if(this._autoResize===null||this._autoResize===undefined){this._autoResize=true;}
this._autoRender=params.autoRender;if(this._autoRender===null||this._autoRender===undefined){this._autoRender=true;}
this._watchScroll=params.watchScroll;if(this._watchScroll===null||this._watchScroll===undefined){this._watchScroll=true;}
this.pixelRatio=params.pixelRatio||window.devicePixelRatio||1;params.renderingScale=isNaN(params.renderingScale)?1:parseFloat(params.renderingScale);this._renderingScale=Math.max(0.25,Math.min(1,params.renderingScale));this.premultipliedAlpha=params.premultipliedAlpha||false;this.alpha=params.alpha;if(this.alpha===null||this.alpha===undefined){this.alpha=true;}
this.antialias=params.antialias;if(this.antialias===null||this.antialias===undefined){this.antialias=true;}
this.productionMode=params.production||false;if(!this.container){if(!this.productionMode)console.warn("You must specify a valid container ID");if(this._onErrorCallback){this._onErrorCallback()}
return;}
this._init();}
Curtains.prototype._init=function(){this.glCanvas=document.createElement("canvas");var glAttributes={alpha:this.alpha,premultipliedAlpha:this.premultipliedAlpha,antialias:this.antialias,};this.gl=this.glCanvas.getContext("webgl2",glAttributes);this._isWebGL2=!!this.gl;if(!this.gl){this.gl=this.glCanvas.getContext("webgl",glAttributes)||this.glCanvas.getContext("experimental-webgl",glAttributes);}
if(!this.gl){if(!this.productionMode)console.warn("WebGL context could not be created");if(this._onErrorCallback){this._onErrorCallback()}
return;}
this._getExtensions();this._glState={currentProgramID:null,programs:[],currentBuffersID:0,setDepth:null,frameBufferID:null,scenePassIndex:null,cullFace:null,flipY:null,};this._contextLostHandler=this._contextLost.bind(this);this.glCanvas.addEventListener("webglcontextlost",this._contextLostHandler,false);this._contextRestoredHandler=this._contextRestored.bind(this);this.glCanvas.addEventListener("webglcontextrestored",this._contextRestoredHandler,false);this._scrollManager={handler:this._scroll.bind(this,true),shouldWatch:this._watchScroll,xOffset:window.pageXOffset,yOffset:window.pageYOffset,lastXDelta:0,lastYDelta:0,};if(this._watchScroll){window.addEventListener("scroll",this._scrollManager.handler,{passive:true});}
this.setPixelRatio(this.pixelRatio,false);this._resizeHandler=null;if(this._autoResize){this._resizeHandler=this.resize.bind(this,true);window.addEventListener("resize",this._resizeHandler,false);}
this._readyToDraw();};Curtains.prototype._getExtensions=function(){this._extensions=[];if(this._isWebGL2){this._extensions['EXT_color_buffer_float']=this.gl.getExtension('EXT_color_buffer_float');this._extensions['OES_texture_float_linear']=this.gl.getExtension('OES_texture_float_linear');this._extensions['WEBGL_lose_context']=this.gl.getExtension('WEBGL_lose_context');}else{this._extensions['OES_vertex_array_object']=this.gl.getExtension('OES_vertex_array_object');this._extensions['OES_texture_float']=this.gl.getExtension('OES_texture_float');this._extensions['OES_texture_float_linear']=this.gl.getExtension('OES_texture_float_linear');this._extensions['OES_texture_half_float']=this.gl.getExtension('OES_texture_half_float');this._extensions['OES_texture_half_float_linear']=this.gl.getExtension('OES_texture_half_float_linear');this._extensions['OES_element_index_uint']=this.gl.getExtension('OES_element_index_uint');this._extensions['OES_standard_derivatives']=this.gl.getExtension('OES_standard_derivatives');this._extensions['EXT_sRGB']=this.gl.getExtension('EXT_sRGB');this._extensions['WEBGL_depth_texture']=this.gl.getExtension('WEBGL_depth_texture');this._extensions['WEBGL_draw_buffers']=this.gl.getExtension('WEBGL_draw_buffers');this._extensions['WEBGL_lose_context']=this.gl.getExtension('WEBGL_lose_context');}};Curtains.prototype.setPixelRatio=function(pixelRatio,triggerCallback){this.pixelRatio=parseFloat(Math.max(pixelRatio,1))||1;this.resize(triggerCallback);};Curtains.prototype._setSize=function(){var containerBoundingRect=this.container.getBoundingClientRect();this._boundingRect={width:containerBoundingRect.width*this.pixelRatio,height:containerBoundingRect.height*this.pixelRatio,top:containerBoundingRect.top*this.pixelRatio,left:containerBoundingRect.left*this.pixelRatio,};var isSafari=!!navigator.userAgent.match(/Version\/[\d\.]+.*Safari/);var iOS=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream;if(isSafari&&iOS){function getTopOffset(el){var topOffset=0;while(el&&!isNaN(el.offsetTop)){topOffset+=el.offsetTop-el.scrollTop;el=el.offsetParent;}
return topOffset;}
this._boundingRect.top=getTopOffset(this.container)*this.pixelRatio;}
this.glCanvas.style.width=Math.floor(this._boundingRect.width / this.pixelRatio)+"px";this.glCanvas.style.height=Math.floor(this._boundingRect.height / this.pixelRatio)+"px";this.glCanvas.width=Math.floor(this._boundingRect.width*this._renderingScale);this.glCanvas.height=Math.floor(this._boundingRect.height*this._renderingScale);this.gl.viewport(0,0,this.gl.drawingBufferWidth,this.gl.drawingBufferHeight);if(this._scrollManager.shouldWatch){this._scrollManager.xOffset=window.pageXOffset;this._scrollManager.yOffset=window.pageYOffset;}};Curtains.prototype.getBoundingRect=function(){return this._boundingRect;};Curtains.prototype.resize=function(triggerCallback){this._setSize();for(var i=0;i<this.planes.length;i++){if(this.planes[i]._canDraw){this.planes[i].planeResize();}}
for(var i=0;i<this.shaderPasses.length;i++){if(this.shaderPasses[i]._canDraw){this.shaderPasses[i].planeResize();}}
for(var i=0;i<this.renderTargets.length;i++){this.renderTargets[i].resize();}
this.needRender();var self=this;setTimeout(function(){if(self._onAfterResizeCallback&&triggerCallback){self._onAfterResizeCallback();}},0);};Curtains.prototype._scroll=function(){var scrollValues={x:window.pageXOffset,y:window.pageYOffset,};this.updateScrollValues(scrollValues.x,scrollValues.y);if(this._scrollManager.shouldWatch){for(var i=0;i<this.planes.length;i++){if(this.planes[i].watchScroll){this.planes[i].updateScrollPosition();}}
this.needRender();}
if(this._onScrollCallback){this._onScrollCallback();}};Curtains.prototype.updateScrollValues=function(x,y){var lastScrollXValue=this._scrollManager.xOffset;this._scrollManager.xOffset=x;this._scrollManager.lastXDelta=lastScrollXValue-this._scrollManager.xOffset;var lastScrollYValue=this._scrollManager.yOffset;this._scrollManager.yOffset=y;this._scrollManager.lastYDelta=lastScrollYValue-this._scrollManager.yOffset;};Curtains.prototype.getScrollDeltas=function(){return{x:this._scrollManager.lastXDelta,y:this._scrollManager.lastYDelta,};};Curtains.prototype.getScrollValues=function(){return{x:this._scrollManager.xOffset,y:this._scrollManager.yOffset,};};Curtains.prototype.enableDrawing=function(){this._drawingEnabled=true;};Curtains.prototype.disableDrawing=function(){this._drawingEnabled=false;};Curtains.prototype.needRender=function(){this._forceRender=true;};Curtains.prototype._contextLost=function(event){event.preventDefault();this._glState={currentProgramID:null,programs:[],currentBuffersID:0,setDepth:null,frameBufferID:null,scenePassIndex:null,cullFace:null,flipY:null,};if(this._animationFrameID){window.cancelAnimationFrame(this._animationFrameID);}
var self=this;setTimeout(function(){if(self._onContextLostCallback){self._onContextLostCallback();}},0);};Curtains.prototype.restoreContext=function(){if(this.gl&&this._extensions['WEBGL_lose_context']){this._extensions['WEBGL_lose_context'].restoreContext();}
else if(!this.productionMode){if(!this.gl){console.warn("Could not restore context because the context is not defined");}
else if(!this._extensions['WEBGL_lose_context']){console.warn("Could not restore context because the restore context extension is not defined");}}};Curtains.prototype._contextRestored=function(){var isDrawingEnabled=this._drawingEnabled;this._drawingEnabled=false;this._getExtensions();this._setBlendFunc();this._setDepth(true);this._drawStacks={"opaque":{length:0,programs:[],order:[],},"transparent":{length:0,programs:[],order:[],},"renderPasses":[],"scenePasses":[],};this._imageCache=[];for(var i=0;i<this.renderTargets.length;i++){this.renderTargets[i]._restoreContext();}
for(var i=0;i<this.planes.length;i++){this.planes[i]._restoreContext();}
for(var i=0;i<this.shaderPasses.length;i++){this.shaderPasses[i]._restoreContext();}
if(this._onContextRestoredCallback){this._onContextRestoredCallback();}
this._drawingEnabled=isDrawingEnabled;this.needRender();if(this._autoRender){this._animate();}};Curtains.prototype.dispose=function(){this._isDestroying=true;while(this.planes.length>0){this.removePlane(this.planes[0]);}
while(this.shaderPasses.length>0){this.removeShaderPass(this.shaderPasses[0]);}
while(this.renderTargets.length>0){this.removeRenderTarget(this.renderTargets[0]);}
for(var i=0;i<this._glState.programs.length;i++){var program=this._glState.programs[i];this.gl.deleteProgram(program.program);}
this._glState={currentProgramID:null,programs:[],currentBuffersID:0,setDepth:null,frameBufferID:null,scenePassIndex:null,cullFace:null,flipY:null,};var self=this;var deleteInterval=setInterval(function(){if(self.planes.length===0&&self.shaderPasses.length===0&&self.renderTargets.length===0){clearInterval(deleteInterval);self._clear();if(self._animationFrameID){window.cancelAnimationFrame(self._animationFrameID);}
if(this._resizeHandler){window.removeEventListener("resize",self._resizeHandler,false);}
if(this._watchScroll){window.removeEventListener("scroll",this._scrollManager.handler,{passive:true});}
self.glCanvas.removeEventListener("webglcontextlost",self._contextLostHandler,false);self.glCanvas.removeEventListener("webglcontextrestored",self._contextRestoredHandler,false);if(self.gl&&self._extensions['WEBGL_lose_context']){self._extensions['WEBGL_lose_context'].loseContext();}
self.glCanvas.width=self.glCanvas.width;self.gl=null;self.container.removeChild(self.glCanvas);self.container=null;self.glCanvas=null;}},100);};Curtains.prototype._createShader=function(shaderCode,shaderType){var shader=this.gl.createShader(shaderType);this.gl.shaderSource(shader,shaderCode);this.gl.compileShader(shader);if(!this.productionMode){if(!this.gl.getShaderParameter(shader,this.gl.COMPILE_STATUS)){var shaderTypeString=shaderType===this.gl.VERTEX_SHADER?"vertex shader":"fragment shader";var shaderSource=this.gl.getShaderSource(shader);var shaderLines=shaderSource.split('\n');for(var i=0;i<shaderLines.length;i++){shaderLines[i]=(i+1)+': '+shaderLines[i];}
shaderLines=shaderLines.join("\n");console.warn("Errors occurred while compiling the",shaderTypeString,":\n",this.gl.getShaderInfoLog(shader));console.error(shaderLines);return null;}}
return shader;};Curtains.prototype._isEqualShader=function(firstShader,secondShader){var isEqualShader=false;if(firstShader.localeCompare(secondShader)===0){isEqualShader=true;}
return isEqualShader;};Curtains.prototype._setupProgram=function(vs,fs,plane){var existingProgram={};for(var i=0;i<this._glState.programs.length;i++){if(this._isEqualShader(this._glState.programs[i].vsCode,vs)&&this._isEqualShader(this._glState.programs[i].fsCode,fs)){existingProgram=this._glState.programs[i];break;}}
if(existingProgram.program){if(plane.shareProgram){return existingProgram;}
else{var shaders=this._useExistingShaders(existingProgram);return this._createProgram(shaders,plane._type);}}
else{var shaders=this._useNewShaders(vs,fs);if(!shaders){return false;}
else{return this._createProgram(shaders,plane._type);}}};Curtains.prototype._useExistingShaders=function(program){return{vs:{vertexShader:program.vertexShader,vsCode:program.vsCode,},fs:{fragmentShader:program.fragmentShader,fsCode:program.fsCode,}};};Curtains.prototype._useNewShaders=function(vs,fs){var isProgramValid=true;var vertexShader=this._createShader(vs,this.gl.VERTEX_SHADER);var fragmentShader=this._createShader(fs,this.gl.FRAGMENT_SHADER);if(!vertexShader||!fragmentShader){if(!this.productionMode)console.warn("Unable to find or compile the vertex or fragment shader");isProgramValid=false;}
if(isProgramValid){return{vs:{vertexShader:vertexShader,vsCode:vs,},fs:{fragmentShader:fragmentShader,fsCode:fs,}};}
else{return isProgramValid;}};Curtains.prototype._createProgram=function(shadersObject,type){var gl=this.gl;var isProgramValid=true;var webglProgram=gl.createProgram();if(isProgramValid){gl.attachShader(webglProgram,shadersObject.vs.vertexShader);gl.attachShader(webglProgram,shadersObject.fs.fragmentShader);gl.linkProgram(webglProgram);if(!this.productionMode){if(!gl.getProgramParameter(webglProgram,gl.LINK_STATUS)){console.warn("Unable to initialize the shader program.");isProgramValid=false;}}
gl.deleteShader(shadersObject.vs.vertexShader);gl.deleteShader(shadersObject.fs.fragmentShader);}
if(isProgramValid){var program={id:this._glState.programs.length,vsCode:shadersObject.vs.vsCode,vertexShader:shadersObject.vs.vertexShader,fsCode:shadersObject.fs.fsCode,fragmentShader:shadersObject.fs.fragmentShader,program:webglProgram,type:type,};if(type==="Plane"){this._drawStacks["opaque"]["programs"]["program-"+program.id]=[];this._drawStacks["transparent"]["programs"]["program-"+program.id]=[];}
this._glState.programs.push(program);return program;}
else{return isProgramValid;}};Curtains.prototype._useProgram=function(program){if(this._glState.currentProgramID===null||this._glState.currentProgramID!==program.id){this.gl.useProgram(program.program);this._glState.currentProgramID=program.id;}};Curtains.prototype.addPlane=function(planeHtmlElement,params){if(!this.gl){if(!this.productionMode)console.warn("Unable to create a plane. The WebGl context couldn't be created");if(this._onErrorCallback){this._onErrorCallback()}
return null;}
else{if(!planeHtmlElement||planeHtmlElement.length===0){if(!this.productionMode)console.warn("The html element you specified does not currently exists in the DOM");if(this._onErrorCallback){this._onErrorCallback()}
return false;}
var plane=new Curtains.Plane(this,planeHtmlElement,params);if(!plane._usedProgram){plane=false;}
else{this.planes.push(plane);}
return plane;}};Curtains.prototype.removePlane=function(plane){plane._canDraw=false;var stackType=plane._transparent?"transparent":"opaque";plane&&plane._dispose();var planeIndex;for(var i=0;i<this.planes.length;i++){if(plane.uuid===this.planes[i].uuid){planeIndex=i;}}
plane=null;this.planes[planeIndex]=null;this.planes.splice(planeIndex,1);for(var i=0;i<this._glState.programs.length;i++){this._drawStacks["opaque"]["programs"]["program-"+this._glState.programs[i].id]=[];this._drawStacks["transparent"]["programs"]["program-"+this._glState.programs[i].id]=[];}
this._drawStacks["opaque"].length=0;this._drawStacks["transparent"].length=0;for(var i=0;i<this.planes.length;i++){var plane=this.planes[i];plane.index=i;var planeStackType=plane._transparent?"transparent":"opaque";if(planeStackType==="transparent"){this._drawStacks[planeStackType]["programs"]["program-"+plane._usedProgram.id].unshift(plane.index);}
else{this._drawStacks[planeStackType]["programs"]["program-"+plane._usedProgram.id].push(plane.index);}
this._drawStacks[planeStackType].length++;}
for(var i=0;i<this._drawStacks[stackType]["order"].length;i++){var programID=this._drawStacks[stackType]["order"][i];if(this._drawStacks[stackType]["programs"]["program-"+programID].length===0){this._drawStacks[stackType]["order"].splice(i,1);}}
if(this.gl)this._clear();this._glState.currentBuffersID=0;};Curtains.prototype._stackPlane=function(plane){var stackType=plane._transparent?"transparent":"opaque";var drawStack=this._drawStacks[stackType];if(stackType==="transparent"){drawStack["programs"]["program-"+plane._usedProgram.id].unshift(plane.index);if(!drawStack["order"].includes(plane._usedProgram.id)){drawStack["order"].unshift(plane._usedProgram.id);}}
else{drawStack["programs"]["program-"+plane._usedProgram.id].push(plane.index);if(!drawStack["order"].includes(plane._usedProgram.id)){drawStack["order"].push(plane._usedProgram.id);}}
drawStack.length++;};Curtains.prototype.addRenderTarget=function(params){if(!this.gl){if(!this.productionMode)console.warn("Unable to create a render target. The WebGl context couldn't be created");if(this._onErrorCallback){this._onErrorCallback()}
return null;}
else{var renderTarget=new Curtains.RenderTarget(this,params);return renderTarget;}};Curtains.prototype.removeRenderTarget=function(renderTarget){if(renderTarget._shaderPass){if(!this.productionMode){console.warn("You're trying to remove a render target attached to a shader pass. You should remove that shader pass instead:",renderTarget._shaderPass);}
return;}
for(var i=0;i<this.planes.length;i++){if(this.planes[i].target&&this.planes[i].target.uuid===renderTarget.uuid){this.planes[i].target=null;}}
var fboIndex;for(var i=0;i<this.renderTargets.length;i++){if(renderTarget.uuid===this.renderTargets[i].uuid){fboIndex=i;}}
this.renderTargets[fboIndex]=null;this.renderTargets.splice(fboIndex,1);renderTarget&&renderTarget._dispose();renderTarget=null;if(this.gl)this._clear();this._glState.currentBuffersID=0;};Curtains.prototype.addShaderPass=function(params){if(!this.gl){if(!this.productionMode)console.warn("Unable to create a shader pass. The WebGl context couldn't be created");if(this._onErrorCallback){this._onErrorCallback()}
return null;}
else{var shaderPass=new Curtains.ShaderPass(this,params);if(!shaderPass._usedProgram){shaderPass=false;}
else{if(params.renderTarget){this._drawStacks.renderPasses.push(shaderPass.index);}
else{this._drawStacks.scenePasses.push(shaderPass.index);}
this.shaderPasses.push(shaderPass);}
return shaderPass;}};Curtains.prototype.removeShaderPass=function(plane){plane._canDraw=false;if(plane.target){plane.target._shaderPass=null;this.removeRenderTarget(plane.target);plane.target=null;}
var planeIndex;for(var i=0;i<this.shaderPasses.length;i++){if(plane.uuid===this.shaderPasses[i].uuid){planeIndex=i;}}
this.shaderPasses.splice(planeIndex,1);this._drawStacks.scenePasses=[];this._drawStacks.renderPasses=[];for(var i=0;i<this.shaderPasses.length;i++){this.shaderPasses[i].index=i;if(this.shaderPasses[i]._isScenePass){this._drawStacks.scenePasses.push(this.shaderPasses[i].index);}
else{this._drawStacks.renderPasses.push(this.shaderPasses[i].index);}}
if(this._drawStacks.scenePasses.length===0){this._glState.scenePassIndex=null;}
plane&&plane._dispose();plane=null;if(this.gl)this._clear();this._glState.currentBuffersID=0;};Curtains.prototype._clear=function(){this.gl.clear(this.gl.COLOR_BUFFER_BIT|this.gl.DEPTH_BUFFER_BIT);};Curtains.prototype._bindFrameBuffer=function(frameBuffer,cancelClear){var bufferId=null;if(frameBuffer){bufferId=frameBuffer.index;if(bufferId!==this._glState.frameBufferID){this.gl.bindFramebuffer(this.gl.FRAMEBUFFER,frameBuffer._frameBuffer);this.gl.viewport(0,0,frameBuffer._size.width,frameBuffer._size.height);if(frameBuffer._shouldClear&&!cancelClear){this._clear();}}}
else if(this._glState.frameBufferID!==null){this.gl.bindFramebuffer(this.gl.FRAMEBUFFER,null);this.gl.viewport(0,0,this.gl.drawingBufferWidth,this.gl.drawingBufferHeight);}
this._glState.frameBufferID=bufferId;};Curtains.prototype._setDepth=function(setDepth){if(setDepth&&!this._glState.depthTest){this._glState.depthTest=setDepth;this.gl.enable(this.gl.DEPTH_TEST);}
else if(!setDepth&&this._glState.depthTest){this._glState.depthTest=setDepth;this.gl.disable(this.gl.DEPTH_TEST);}};Curtains.prototype._setBlendFunc=function(){var gl=this.gl;gl.enable(gl.BLEND);if(this.premultipliedAlpha){gl.blendFuncSeparate(gl.ONE,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);}
else{gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);}};Curtains.prototype._setFaceCulling=function(cullFace){var gl=this.gl;if(this._glState.cullFace!==cullFace){this._glState.cullFace=cullFace;if(cullFace==="none"){gl.disable(gl.CULL_FACE);}
else{var faceCulling=cullFace==="front"?gl.FRONT:gl.BACK;gl.enable(gl.CULL_FACE);gl.cullFace(faceCulling);}}};Curtains.prototype._generateUUID=function(){return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=='x'?r:(r&0x3|0x8);return v.toString(16).toUpperCase();});};Curtains.prototype._multiplyMatrix=function(a,b){var out=new Float32Array(16);out[0]=b[0]*a[0]+b[1]*a[4]+b[2]*a[8]+b[3]*a[12];out[1]=b[0]*a[1]+b[1]*a[5]+b[2]*a[9]+b[3]*a[13];out[2]=b[0]*a[2]+b[1]*a[6]+b[2]*a[10]+b[3]*a[14];out[3]=b[0]*a[3]+b[1]*a[7]+b[2]*a[11]+b[3]*a[15];out[4]=b[4]*a[0]+b[5]*a[4]+b[6]*a[8]+b[7]*a[12];out[5]=b[4]*a[1]+b[5]*a[5]+b[6]*a[9]+b[7]*a[13];out[6]=b[4]*a[2]+b[5]*a[6]+b[6]*a[10]+b[7]*a[14];out[7]=b[4]*a[3]+b[5]*a[7]+b[6]*a[11]+b[7]*a[15];out[8]=b[8]*a[0]+b[9]*a[4]+b[10]*a[8]+b[11]*a[12];out[9]=b[8]*a[1]+b[9]*a[5]+b[10]*a[9]+b[11]*a[13];out[10]=b[8]*a[2]+b[9]*a[6]+b[10]*a[10]+b[11]*a[14];out[11]=b[8]*a[3]+b[9]*a[7]+b[10]*a[11]+b[11]*a[15];out[12]=b[12]*a[0]+b[13]*a[4]+b[14]*a[8]+b[15]*a[12];out[13]=b[12]*a[1]+b[13]*a[5]+b[14]*a[9]+b[15]*a[13];out[14]=b[12]*a[2]+b[13]*a[6]+b[14]*a[10]+b[15]*a[14];out[15]=b[12]*a[3]+b[13]*a[7]+b[14]*a[11]+b[15]*a[15];return out;};Curtains.prototype._scaleMatrix=function(matrix,scaleX,scaleY,scaleZ){var scaledMatrix=new Float32Array(16);scaledMatrix[0]=scaleX*matrix[0*4+0];scaledMatrix[1]=scaleX*matrix[0*4+1];scaledMatrix[2]=scaleX*matrix[0*4+2];scaledMatrix[3]=scaleX*matrix[0*4+3];scaledMatrix[4]=scaleY*matrix[1*4+0];scaledMatrix[5]=scaleY*matrix[1*4+1];scaledMatrix[6]=scaleY*matrix[1*4+2];scaledMatrix[7]=scaleY*matrix[1*4+3];scaledMatrix[8]=scaleZ*matrix[2*4+0];scaledMatrix[9]=scaleZ*matrix[2*4+1];scaledMatrix[10]=scaleZ*matrix[2*4+2];scaledMatrix[11]=scaleZ*matrix[2*4+3];if(matrix!==scaledMatrix){scaledMatrix[12]=matrix[12];scaledMatrix[13]=matrix[13];scaledMatrix[14]=matrix[14];scaledMatrix[15]=matrix[15];}
return scaledMatrix;};Curtains.prototype._composeMatrixFromOrigin=function(translation,quaternion,scale,origin){var matrix=new Float32Array(16);var x=quaternion[0],y=quaternion[1],z=quaternion[2],w=quaternion[3];var x2=x+x;var y2=y+y;var z2=z+z;var xx=x*x2;var xy=x*y2;var xz=x*z2;var yy=y*y2;var yz=y*z2;var zz=z*z2;var wx=w*x2;var wy=w*y2;var wz=w*z2;var sx=scale.x;var sy=scale.y;var sz=1;var ox=origin.x;var oy=origin.y;var oz=origin.z;var out0=(1-(yy+zz))*sx;var out1=(xy+wz)*sx;var out2=(xz-wy)*sx;var out4=(xy-wz)*sy;var out5=(1-(xx+zz))*sy;var out6=(yz+wx)*sy;var out8=(xz+wy)*sz;var out9=(yz-wx)*sz;var out10=(1-(xx+yy))*sz;matrix[0]=out0;matrix[1]=out1;matrix[2]=out2;matrix[3]=0;matrix[4]=out4;matrix[5]=out5;matrix[6]=out6;matrix[7]=0;matrix[8]=out8;matrix[9]=out9;matrix[10]=out10;matrix[11]=0;matrix[12]=translation.x+ox-(out0*ox+out4*oy+out8*oz);matrix[13]=translation.y+oy-(out1*ox+out5*oy+out9*oz);matrix[14]=translation.z+oz-(out2*ox+out6*oy+out10*oz);matrix[15]=1;return matrix;};Curtains.prototype._applyMatrixToPoint=function(point,matrix){var transformedPoint=[];var x=point[0],y=point[1],z=point[2];transformedPoint[0]=matrix[0]*x+matrix[4]*y+matrix[8]*z+matrix[12];transformedPoint[1]=matrix[1]*x+matrix[5]*y+matrix[9]*z+matrix[13];transformedPoint[2]=matrix[2]*x+matrix[6]*y+matrix[10]*z+matrix[14];var w=matrix[3]*x+matrix[7]*y+matrix[11]*z+matrix[15];w=w||1;transformedPoint[0]/=w;transformedPoint[1]/=w;transformedPoint[2]/=w;return transformedPoint;};Curtains.prototype._readyToDraw=function(){this.container.appendChild(this.glCanvas);this._setBlendFunc();this._setDepth(true);console.log("curtains.js - v6.1");this._animationFrameID=null;if(this._autoRender){this._animate();}};Curtains.prototype._animate=function(){this.render();this._animationFrameID=window.requestAnimationFrame(this._animate.bind(this));};Curtains.prototype._drawPlaneStack=function(stackType){for(var i=0;i<this._drawStacks[stackType]["order"].length;i++){var programID=this._drawStacks[stackType]["order"][i];var program=this._drawStacks[stackType]["programs"]["program-"+programID];for(var j=0;j<program.length;j++){var plane=this.planes[program[j]];if(plane){plane._drawPlane();}}}};Curtains.prototype.render=function(){if(!this._drawingEnabled&&!this._forceRender)return;if(this._forceRender){this._forceRender=false;}
if(this._onRenderCallback){this._onRenderCallback();}
this._clear();if(this._drawStacks.scenePasses.length>0&&this._drawStacks.renderPasses.length===0){this._glState.scenePassIndex=0;this._bindFrameBuffer(this.shaderPasses[this._drawStacks.scenePasses[0]].target);}
this._drawPlaneStack("opaque");if(this._drawStacks["transparent"].length){this.gl.clearDepth(1.0);this.gl.clear(this.gl.DEPTH_BUFFER_BIT);this._drawPlaneStack("transparent");}
if(this._drawStacks.scenePasses.length>0&&this._drawStacks.renderPasses.length>0){this._glState.scenePassIndex=0;this._bindFrameBuffer(this.shaderPasses[this._drawStacks.scenePasses[0]].target);}
for(var i=0;i<this._drawStacks.renderPasses.length;i++){var renderPass=this.shaderPasses[this._drawStacks.renderPasses[i]];renderPass._drawPlane();}
if(this._drawStacks.scenePasses.length>0){for(var i=0;i<this._drawStacks.scenePasses.length;i++){var scenePass=this.shaderPasses[this._drawStacks.scenePasses[i]];scenePass._drawPlane();}}};Curtains.prototype.onAfterResize=function(callback){if(callback){this._onAfterResizeCallback=callback;}
return this;};Curtains.prototype.onError=function(callback){if(callback){this._onErrorCallback=callback;}
return this;};Curtains.prototype.onContextLost=function(callback){if(callback){this._onContextLostCallback=callback;}
return this;};Curtains.prototype.onContextRestored=function(callback){if(callback){this._onContextRestoredCallback=callback;}
return this;};Curtains.prototype.onRender=function(callback){if(callback){this._onRenderCallback=callback;}
return this;};Curtains.prototype.onScroll=function(callback){if(callback){this._onScrollCallback=callback;}
return this;};Curtains.BasePlane=function(curtainWrapper,plane,params){this._type=this._type||"BasicPlane";this._curtains=curtainWrapper;this.htmlElement=plane;this.uuid=this._curtains._generateUUID();this._initBasePlane(params);};Curtains.BasePlane.prototype._initBasePlane=function(params){if(!params)params={};this._canDraw=false;this.shareProgram=params.shareProgram||false;this._updatePerspectiveMatrix=false;this._updateMVMatrix=false;this._definition={width:parseInt(params.widthSegments)||1,height:parseInt(params.heightSegments)||1,};this._definition.buffersID=this._definition.width*this._definition.height+this._definition.width;this._depthTest=params.depthTest;if(this._depthTest===null||this._depthTest===undefined){this._depthTest=true;}
this.cullFace=params.cullFace;if(this.cullFace!=="back"&&this.cullFace!=="front"&&this.cullFace!=="none"){this.cullFace="back";}
this._activeTextures=[];if(!params.uniforms){params.uniforms={};}
this.uniforms={};if(params.uniforms){for(var key in params.uniforms){var uniform=params.uniforms[key];this.uniforms[key]={name:uniform.name,type:uniform.type,value:uniform.value,lastValue:uniform.value,};}}
var shaders=this._setupShaders(params);this._usedProgram=this._curtains._setupProgram(shaders.vertexShaderCode,shaders.fragmentShaderCode,this);this._loadingManager={sourcesLoaded:0,initSourcesToLoad:0,complete:false,};this.images=[];this.videos=[];this.canvases=[];this.textures=[];this.crossOrigin=params.crossOrigin||"anonymous";this.userData={};if(this._usedProgram){this._shouldDraw=true;this.visible=true;this._setAttributes();this._setDocumentSizes();this._setUniforms();this._initializeBuffers();this._canDraw=true;return this;}
else{return false;}};Curtains.BasePlane.prototype._getDefaultVS=function(){if(!this._curtains.productionMode)console.warn("No vertex shader provided, will use a default one");return"precision mediump float;\nattribute vec3 aVertexPosition;attribute vec2 aTextureCoord;uniform mat4 uMVMatrix;uniform mat4 uPMatrix;varying vec3 vVertexPosition;varying vec2 vTextureCoord;void main() {vTextureCoord = aTextureCoord;vVertexPosition = aVertexPosition;gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);}";};Curtains.BasePlane.prototype._getDefaultFS=function(){return"precision mediump float;\nvarying vec3 vVertexPosition;varying vec2 vTextureCoord;void main( void ) {gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);}";};Curtains.BasePlane.prototype._setupShaders=function(params){var vsId=params.vertexShaderID||this.htmlElement.getAttribute("data-vs-id");var fsId=params.fragmentShaderID||this.htmlElement.getAttribute("data-fs-id");var vsIdHTML,fsIdHTML;if(!params.vertexShader){if(!vsId||!document.getElementById(vsId)){vsIdHTML=this._getDefaultVS();}
else{vsIdHTML=document.getElementById(vsId).innerHTML;}}
if(!params.fragmentShader){if(!fsId||!document.getElementById(fsId)){if(!this._curtains.productionMode)console.warn("No fragment shader provided, will use a default one");fsIdHTML=this._getDefaultFS();}
else{fsIdHTML=document.getElementById(fsId).innerHTML;}}
return{vertexShaderCode:params.vertexShader||vsIdHTML,fragmentShaderCode:params.fragmentShader||fsIdHTML,}};Curtains.BasePlane.prototype._handleUniformSetting=function(uniformType,uniformLocation,uniformValue){var gl=this._curtains.gl;switch(uniformType){case"1i":gl.uniform1i(uniformLocation,uniformValue);break;case"1iv":gl.uniform1iv(uniformLocation,uniformValue);break;case"1f":gl.uniform1f(uniformLocation,uniformValue);break;case"1fv":gl.uniform1fv(uniformLocation,uniformValue);break;case"2i":gl.uniform2i(uniformLocation,uniformValue[0],uniformValue[1]);break;case"2iv":gl.uniform2iv(uniformLocation,uniformValue);break;case"2f":gl.uniform2f(uniformLocation,uniformValue[0],uniformValue[1]);break;case"2fv":gl.uniform2fv(uniformLocation,uniformValue);break;case"3i":gl.uniform3i(uniformLocation,uniformValue[0],uniformValue[1],uniformValue[2]);break;case"3iv":gl.uniform3iv(uniformLocation,uniformValue);break;case"3f":gl.uniform3f(uniformLocation,uniformValue[0],uniformValue[1],uniformValue[2]);break;case"3fv":gl.uniform3fv(uniformLocation,uniformValue);break;case"4i":gl.uniform4i(uniformLocation,uniformValue[0],uniformValue[1],uniformValue[2],uniformValue[3]);break;case"4iv":gl.uniform4iv(uniformLocation,uniformValue);break;case"4f":gl.uniform4f(uniformLocation,uniformValue[0],uniformValue[1],uniformValue[2],uniformValue[3]);break;case"4fv":gl.uniform4fv(uniformLocation,uniformValue);break;case"mat2":gl.uniformMatrix2fv(uniformLocation,false,uniformValue);break;case"mat3":gl.uniformMatrix3fv(uniformLocation,false,uniformValue);break;case"mat4":gl.uniformMatrix4fv(uniformLocation,false,uniformValue);break;default:if(!this._curtains.productionMode)console.warn("This uniform type is not handled : ",uniformType);}};Curtains.BasePlane.prototype._setUniforms=function(){var curtains=this._curtains;var gl=curtains.gl;curtains._useProgram(this._usedProgram);var numUniforms=gl.getProgramParameter(this._usedProgram.program,gl.ACTIVE_UNIFORMS);for(var i=0;i<numUniforms;i++){var activeUniform=gl.getActiveUniform(this._usedProgram.program,i);if(activeUniform.type===gl.SAMPLER_2D){this._activeTextures.push(activeUniform);}}
if(this.uniforms){for(var key in this.uniforms){var uniform=this.uniforms[key];uniform.location=gl.getUniformLocation(this._usedProgram.program,uniform.name);if(!uniform.type){if(Array.isArray(uniform.value)){if(uniform.value.length===4){uniform.type="4f";if(!curtains.productionMode)console.warn("No uniform type declared for "+uniform.name+", applied a 4f (array of 4 floats) uniform type");}
else if(uniform.value.length===3){uniform.type="3f";if(!curtains.productionMode)console.warn("No uniform type declared for "+uniform.name+", applied a 3f (array of 3 floats) uniform type");}
else if(uniform.value.length===2){uniform.type="2f";if(!curtains.productionMode)console.warn("No uniform type declared for "+uniform.name+", applied a 2f (array of 2 floats) uniform type");}}
else if(uniform.value.constructor===Float32Array){if(uniform.value.length===16){uniform.type="mat4";if(!curtains.productionMode)console.warn("No uniform type declared for "+uniform.name+", applied a mat4 (4x4 matrix array) uniform type");}
else if(uniform.value.length===9){uniform.type="mat3";if(!curtains.productionMode)console.warn("No uniform type declared for "+uniform.name+", applied a mat3 (3x3 matrix array) uniform type");}
else if(uniform.value.length===4){uniform.type="mat2";if(!curtains.productionMode)console.warn("No uniform type declared for "+uniform.name+", applied a mat2 (2x2 matrix array) uniform type");}}
else{uniform.type="1f";if(!curtains.productionMode)console.warn("No uniform type declared for "+uniform.name+", applied a 1f (float) uniform type");}}
this._handleUniformSetting(uniform.type,uniform.location,uniform.value);}}};Curtains.BasePlane.prototype._updateUniforms=function(){if(this.uniforms){for(var key in this.uniforms){var uniform=this.uniforms[key];if(!this.shareProgram){if(!uniform.value.length&&uniform.value!==uniform.lastValue){this._handleUniformSetting(uniform.type,uniform.location,uniform.value);}
else if(JSON.stringify(uniform.value)!==JSON.stringify(uniform.lastValue)){this._handleUniformSetting(uniform.type,uniform.location,uniform.value);}
uniform.lastValue=uniform.value;}
else{this._handleUniformSetting(uniform.type,uniform.location,uniform.value);}}}};Curtains.BasePlane.prototype._setAttributes=function(){if(!this._attributes)this._attributes={};this._attributes.vertexPosition={name:"aVertexPosition",location:this._curtains.gl.getAttribLocation(this._usedProgram.program,"aVertexPosition"),};this._attributes.textureCoord={name:"aTextureCoord",location:this._curtains.gl.getAttribLocation(this._usedProgram.program,"aTextureCoord"),};};Curtains.BasePlane.prototype._setPlaneVertices=function(){this._geometry={vertices:[],};this._material={uvs:[],};for(var y=0;y<this._definition.height;++y){var v=y / this._definition.height;for(var x=0;x<this._definition.width;++x){var u=x / this._definition.width;this._material.uvs.push(u);this._material.uvs.push(v);this._material.uvs.push(0);this._geometry.vertices.push((u-0.5)*2);this._geometry.vertices.push((v-0.5)*2);this._geometry.vertices.push(0);this._material.uvs.push(u+(1 / this._definition.width));this._material.uvs.push(v);this._material.uvs.push(0);this._geometry.vertices.push(((u+(1 / this._definition.width))-0.5)*2);this._geometry.vertices.push((v-0.5)*2);this._geometry.vertices.push(0);this._material.uvs.push(u);this._material.uvs.push(v+(1 / this._definition.height));this._material.uvs.push(0);this._geometry.vertices.push((u-0.5)*2);this._geometry.vertices.push(((v+(1 / this._definition.height))-0.5)*2);this._geometry.vertices.push(0);this._material.uvs.push(u);this._material.uvs.push(v+(1 / this._definition.height));this._material.uvs.push(0);this._geometry.vertices.push((u-0.5)*2);this._geometry.vertices.push(((v+(1 / this._definition.height))-0.5)*2);this._geometry.vertices.push(0);this._material.uvs.push(u+(1 / this._definition.width));this._material.uvs.push(v);this._material.uvs.push(0);this._geometry.vertices.push(((u+(1 / this._definition.width))-0.5)*2);this._geometry.vertices.push((v-0.5)*2);this._geometry.vertices.push(0);this._material.uvs.push(u+(1 / this._definition.width));this._material.uvs.push(v+(1 / this._definition.height));this._material.uvs.push(0);this._geometry.vertices.push(((u+(1 / this._definition.width))-0.5)*2);this._geometry.vertices.push(((v+(1 / this._definition.height))-0.5)*2);this._geometry.vertices.push(0);}}};Curtains.BasePlane.prototype._initializeBuffers=function(){var gl=this._curtains.gl;if(!this._geometry&&!this._material){this._setPlaneVertices();}
if(!this._attributes)return;this._geometry.bufferInfos={id:gl.createBuffer(),itemSize:3,numberOfItems:this._geometry.vertices.length / 3,};this._material.bufferInfos={id:gl.createBuffer(),itemSize:3,numberOfItems:this._material.uvs.length / 3,};if(this._curtains._isWebGL2){this._vao=gl.createVertexArray();gl.bindVertexArray(this._vao);}
else if(this._curtains._extensions['OES_vertex_array_object']){this._vao=this._curtains._extensions['OES_vertex_array_object'].createVertexArrayOES();this._curtains._extensions['OES_vertex_array_object'].bindVertexArrayOES(this._vao);}
gl.enableVertexAttribArray(this._attributes.vertexPosition.location);gl.bindBuffer(gl.ARRAY_BUFFER,this._geometry.bufferInfos.id);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(this._geometry.vertices),gl.STATIC_DRAW);gl.vertexAttribPointer(this._attributes.vertexPosition.location,this._geometry.bufferInfos.itemSize,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(this._attributes.textureCoord.location);gl.bindBuffer(gl.ARRAY_BUFFER,this._material.bufferInfos.id);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(this._material.uvs),gl.STATIC_DRAW);gl.vertexAttribPointer(this._attributes.textureCoord.location,this._material.bufferInfos.itemSize,gl.FLOAT,false,0,0);this._curtains._glState.currentBuffersID=this._definition.buffersID;};Curtains.BasePlane.prototype._restoreContext=function(){var curtains=this._curtains;this._canDraw=false;if(this._matrices){this._matrices=null;}
this._attributes=null;this._geometry.bufferInfos=null;this._material.bufferInfos=null;this._usedProgram=curtains._setupProgram(this._usedProgram.vsCode,this._usedProgram.fsCode,this);if(this._usedProgram){this._setAttributes();this._activeTextures=[];this._setUniforms();this._initializeBuffers();if(this._type==="ShaderPass"){if(this._isScenePass){this.target._frameBuffer=null;this.target._depthBuffer=null;curtains.renderTargets.splice(this.target.index,1);this.textures.splice(0,1);this._createFrameBuffer();curtains._drawStacks.scenePasses.push(this.index);}
else{var target=curtains.renderTargets[this.target.index];this.setRenderTarget(target);this.target._shaderPass=target;this.textures[0]._canDraw=false;this.textures[0]._setTextureUniforms();this.textures[0].setFromTexture(target.textures[0]);curtains._drawStacks.renderPasses.push(this.index);}}
else if(this.target){this.setRenderTarget(curtains.renderTargets[this.target.index]);}
for(var i=this._type==="ShaderPass"?1:0;i<this.textures.length;i++){this.textures[i]._restoreContext();}
if(this._type==="Plane"){this._initMatrices();this.setPerspective(this._fov,this._nearPlane,this._farPlane);this._applyWorldPositions();curtains._stackPlane(this);}
this._canDraw=true;}};Curtains.BasePlane.prototype._setDocumentSizes=function(){var planeBoundingRect=this.htmlElement.getBoundingClientRect();if(planeBoundingRect.width===0&&planeBoundingRect.height===0){planeBoundingRect=this._curtains._boundingRect;}
if(!this._boundingRect)this._boundingRect={};this._boundingRect.document={width:planeBoundingRect.width*this._curtains.pixelRatio,height:planeBoundingRect.height*this._curtains.pixelRatio,top:planeBoundingRect.top*this._curtains.pixelRatio,left:planeBoundingRect.left*this._curtains.pixelRatio,};};Curtains.BasePlane.prototype.getBoundingRect=function(){return{width:this._boundingRect.document.width,height:this._boundingRect.document.height,top:this._boundingRect.document.top,left:this._boundingRect.document.left,right:this._boundingRect.document.left+this._boundingRect.document.width,bottom:this._boundingRect.document.top+this._boundingRect.document.height,};};Curtains.BasePlane.prototype._getNearPlaneIntersections=function(corners,mvpCorners,clippedCorners){function getIntersection(refPoint,secondPoint){var vector=[secondPoint[0]-refPoint[0],secondPoint[1]-refPoint[1],secondPoint[2]-refPoint[2],];var intersection=refPoint.slice();while(intersection[2]>-1){intersection[0]+=vector[0];intersection[1]+=vector[1];intersection[2]+=vector[2];}
return intersection;}
if(clippedCorners.length===1){if(clippedCorners[0]===0){mvpCorners[0]=getIntersection(mvpCorners[1],this._curtains._applyMatrixToPoint([0.95,1,0],this._matrices.mVPMatrix));mvpCorners.push(getIntersection(mvpCorners[3],this._curtains._applyMatrixToPoint([-1,-0.95,0],this._matrices.mVPMatrix)));}
else if(clippedCorners[0]===1){mvpCorners[1]=getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([-0.95,1,0],this._matrices.mVPMatrix));mvpCorners.push(getIntersection(mvpCorners[2],this._curtains._applyMatrixToPoint([1,-0.95,0],this._matrices.mVPMatrix)));}
else if(clippedCorners[0]===2){mvpCorners[2]=getIntersection(mvpCorners[3],this._curtains._applyMatrixToPoint([-0.95,-1,0],this._matrices.mVPMatrix));mvpCorners.push(getIntersection(mvpCorners[1],this._curtains._applyMatrixToPoint([1,0.95,0],this._matrices.mVPMatrix)));}
else if(clippedCorners[0]===3){mvpCorners[3]=getIntersection(mvpCorners[2],this._curtains._applyMatrixToPoint([0.95,-1,0],this._matrices.mVPMatrix));mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([-1,0.95,0],this._matrices.mVPMatrix)));}}
else if(clippedCorners.length===2){if(clippedCorners[0]===0&&clippedCorners[1]===1){mvpCorners[0]=getIntersection(mvpCorners[3],this._curtains._applyMatrixToPoint([-1,-0.95,0],this._matrices.mVPMatrix));mvpCorners[1]=getIntersection(mvpCorners[2],this._curtains._applyMatrixToPoint([1,-0.95,0],this._matrices.mVPMatrix));}
else if(clippedCorners[0]===1&&clippedCorners[1]===2){mvpCorners[1]=getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([-0.95,1,0],this._matrices.mVPMatrix));mvpCorners[2]=getIntersection(mvpCorners[3],this._curtains._applyMatrixToPoint([-0.95,-1,0],this._matrices.mVPMatrix));}
else if(clippedCorners[0]===2&&clippedCorners[1]===3){mvpCorners[2]=getIntersection(mvpCorners[1],this._curtains._applyMatrixToPoint([1,0.95,0],this._matrices.mVPMatrix));mvpCorners[3]=getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([-1,0.95,0],this._matrices.mVPMatrix));}
else if(clippedCorners[0]===0&&clippedCorners[1]===3){mvpCorners[0]=getIntersection(mvpCorners[1],this._curtains._applyMatrixToPoint([0.95,1,0],this._matrices.mVPMatrix));mvpCorners[3]=getIntersection(mvpCorners[2],this._curtains._applyMatrixToPoint([0.95,-1,0],this._matrices.mVPMatrix));}}
else if(clippedCorners.length===3){var nonClippedCorner=0;for(var i=0;i<corners.length;i++){if(!clippedCorners.includes(i)){nonClippedCorner=i;}}
mvpCorners=[mvpCorners[nonClippedCorner]];if(nonClippedCorner===0){mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([-0.95,1,0],this._matrices.mVPMatrix)));mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([-1,0.95,0],this._matrices.mVPMatrix)));}
else if(nonClippedCorner===1){mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([0.95,1,0],this._matrices.mVPMatrix)));mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([1,0.95,0],this._matrices.mVPMatrix)));}
else if(nonClippedCorner===2){mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([0.95,-1,0],this._matrices.mVPMatrix)));mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([1,-0.95,0],this._matrices.mVPMatrix)));}
else if(nonClippedCorner===3){mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([-0.95,-1,0],this._matrices.mVPMatrix)));mvpCorners.push(getIntersection(mvpCorners[0],this._curtains._applyMatrixToPoint([-1,-0.95,0],this._matrices.mVPMatrix)));}}
else{for(var i=0;i<corners.length;i++){mvpCorners[i][0]=10000;mvpCorners[i][1]=10000;}}
return mvpCorners;};Curtains.BasePlane.prototype._getWorldCoords=function(){var corners=[[-1,1,0],[1,1,0],[1,-1,0],[-1,-1,0],];var mvpCorners=[];var clippedCorners=[];for(var i=0;i<corners.length;i++){var mvpCorner=this._curtains._applyMatrixToPoint(corners[i],this._matrices.mVPMatrix);mvpCorners.push(mvpCorner);if(Math.abs(mvpCorner[2])>1){clippedCorners.push(i);}}
if(clippedCorners.length){mvpCorners=this._getNearPlaneIntersections(corners,mvpCorners,clippedCorners);}
var minX=Infinity;var maxX=-Infinity;var minY=Infinity;var maxY=-Infinity;for(var i=0;i<mvpCorners.length;i++){var corner=mvpCorners[i];if(corner[0]<minX){minX=corner[0];}
if(corner[0]>maxX){maxX=corner[0];}
if(corner[1]<minY){minY=corner[1];}
if(corner[1]>maxY){maxY=corner[1];}}
return{top:maxY,right:maxX,bottom:minY,left:minX,};};Curtains.BasePlane.prototype.getWebGLBoundingRect=function(){if(this._matrices.mVPMatrix){var worldBBox=this._getWorldCoords();var screenBBox={top:1-(worldBBox.top+1)/ 2,right:(worldBBox.right+1)/ 2,bottom:1-(worldBBox.bottom+1)/ 2,left:(worldBBox.left+1)/ 2,};screenBBox.width=screenBBox.right-screenBBox.left;screenBBox.height=screenBBox.bottom-screenBBox.top;return{width:screenBBox.width*this._curtains._boundingRect.width,height:screenBBox.height*this._curtains._boundingRect.height,top:screenBBox.top*this._curtains._boundingRect.height+this._curtains._boundingRect.top,left:screenBBox.left*this._curtains._boundingRect.width+this._curtains._boundingRect.left,right:screenBBox.left*this._curtains._boundingRect.width+this._curtains._boundingRect.left+screenBBox.width*this._curtains._boundingRect.width,bottom:screenBBox.top*this._curtains._boundingRect.height+this._curtains._boundingRect.top+screenBBox.height*this._curtains._boundingRect.height,};}
else{return this._boundingRect.document;}};Curtains.BasePlane.prototype._getWebGLDrawRect=function(){var boundingRect=this.getWebGLBoundingRect();return{top:boundingRect.top-this.drawCheckMargins.top,right:boundingRect.right+this.drawCheckMargins.right,bottom:boundingRect.bottom+this.drawCheckMargins.bottom,left:boundingRect.left-this.drawCheckMargins.left,};};Curtains.BasePlane.prototype.planeResize=function(){this._setDocumentSizes();if(this._type==="Plane"){this.setPerspective(this._fov,this._nearPlane,this._farPlane);this._applyWorldPositions();}
for(var i=0;i<this.textures.length;i++){this.textures[i].resize();}
var self=this;setTimeout(function(){if(self._onAfterResizeCallback){self._onAfterResizeCallback();}},0);};Curtains.BasePlane.prototype.createTexture=function(params){if(typeof params==="string"){params={sampler:params,};if(!this._curtains.productionMode){console.warn("Since v5.1 you should use an object to pass your sampler name with the createTexture() method. Please refer to the docs: https://www.curtainsjs.com/documentation.html (texture concerned: ",params.sampler,")");}}
if(!params)params={};var texture=new Curtains.Texture(this,{index:this.textures.length,sampler:params.sampler||null,fromTexture:params.fromTexture||null,isFBOTexture:params.isFBOTexture||false,});this.textures.push(texture);return texture;};Curtains.BasePlane.prototype._isPlaneReady=function(){if(!this._loadingManager.complete&&this._loadingManager.sourcesLoaded>=this._loadingManager.initSourcesToLoad){this._loadingManager.complete=true;this._curtains.needRender();var self=this;setTimeout(function(){if(self._onReadyCallback){self._onReadyCallback();}},0);}};Curtains.BasePlane.prototype.loadSources=function(sourcesArray){for(var i=0;i<sourcesArray.length;i++){this.loadSource(sourcesArray[i]);}};Curtains.BasePlane.prototype.loadSource=function(source){if(source.tagName.toUpperCase()==="IMG"){this.loadImage(source);}
else if(source.tagName.toUpperCase()==="VIDEO"){this.loadVideo(source);}
else if(source.tagName.toUpperCase()==="CANVAS"){this.loadCanvas(source);}
else if(!this._curtains.productionMode){console.warn("this HTML tag could not be converted into a texture:",source.tagName);}};Curtains.BasePlane.prototype._sourceLoadError=function(source,error){if(!this._curtains.productionMode){console.warn("There has been an error:",error,"while loading this source:",source);}};Curtains.BasePlane.prototype._getTextureFromCache=function(source){var cachedTexture=false;if(this._curtains._imageCache.length>0){for(var i=0;i<this._curtains._imageCache.length;i++){var cacheTextureItem=this._curtains._imageCache[i];if(cacheTextureItem.source){if(cacheTextureItem.type==="image"&&cacheTextureItem.source.src===source.src){cachedTexture=cacheTextureItem;}}}}
return cachedTexture;};Curtains.BasePlane.prototype.loadImage=function(source){var image=source;image.crossOrigin=this.crossOrigin||"anonymous";image.sampler=source.getAttribute("data-sampler")||null;var cachedTexture=this._getTextureFromCache(source);if(cachedTexture){this.createTexture({sampler:image.sampler,fromTexture:cachedTexture,});this.images.push(cachedTexture.source);this._isPlaneReady();return;}
var texture=this.createTexture({sampler:image.sampler,});texture._onSourceLoadedHandler=texture._onSourceLoaded.bind(texture,image);if(image.complete){texture._onSourceLoaded(image);}
else if(image.decode){var self=this;image.decode().then(texture._onSourceLoadedHandler).catch(function(){image.addEventListener('load',texture._onSourceLoadedHandler,false);image.addEventListener('error',self._sourceLoadError.bind(self,image),false);});}
else{image.addEventListener('load',texture._onSourceLoadedHandler,false);image.addEventListener('error',this._sourceLoadError.bind(this,image),false);}
this.images.push(image);};Curtains.BasePlane.prototype.loadVideo=function(source){var video=source;video.preload=true;video.muted=true;video.loop=true;video.sampler=source.getAttribute("data-sampler")||null;video.crossOrigin=this.crossOrigin||"anonymous";var texture=this.createTexture({sampler:video.sampler});texture._onSourceLoadedHandler=texture._onVideoLoadedData.bind(texture,video);video.addEventListener('canplaythrough',texture._onSourceLoadedHandler,false);video.addEventListener('error',this._sourceLoadError.bind(this,video),false);if(video.readyState>=video.HAVE_FUTURE_DATA){texture._onSourceLoaded(video);}
video.load();this.videos.push(video);};Curtains.BasePlane.prototype.loadCanvas=function(source){var canvas=source;canvas.sampler=source.getAttribute("data-sampler")||null;var texture=this.createTexture({sampler:canvas.sampler});this.canvases.push(canvas);texture._onSourceLoaded(canvas);};Curtains.BasePlane.prototype.loadImages=function(imagesArray){for(var i=0;i<imagesArray.length;i++){this.loadImage(imagesArray[i]);}};Curtains.BasePlane.prototype.loadVideos=function(videosArray){for(var i=0;i<videosArray.length;i++){this.loadVideo(videosArray[i]);}};Curtains.BasePlane.prototype.loadCanvases=function(canvasesArray){for(var i=0;i<canvasesArray.length;i++){this.loadCanvas(canvasesArray[i]);}};Curtains.BasePlane.prototype.playVideos=function(){for(var i=0;i<this.textures.length;i++){var texture=this.textures[i];if(texture.type==="video"){var playPromise=texture.source.play();var self=this;if(playPromise!==undefined){playPromise.catch(function(error){if(!self._curtains.productionMode)console.warn("Could not play the video : ",error);});}}}};Curtains.BasePlane.prototype.mouseToPlaneCoords=function(xMousePosition,yMousePosition){var scale=this.scale?this.scale:{x:1,y:1};var scaleAdjustment={x:(this._boundingRect.document.width-this._boundingRect.document.width*scale.x)/ 2,y:(this._boundingRect.document.height-this._boundingRect.document.height*scale.y)/ 2,};var planeBoundingRect={width:(this._boundingRect.document.width*scale.x)/ this._curtains.pixelRatio,height:(this._boundingRect.document.height*scale.y)/ this._curtains.pixelRatio,top:(this._boundingRect.document.top+scaleAdjustment.y)/ this._curtains.pixelRatio,left:(this._boundingRect.document.left+scaleAdjustment.x)/ this._curtains.pixelRatio,};var mousePosition={x:(((xMousePosition-planeBoundingRect.left)/ planeBoundingRect.width)*2)-1,y:1-(((yMousePosition-planeBoundingRect.top)/ planeBoundingRect.height)*2)};return mousePosition;};Curtains.BasePlane.prototype._bindPlaneBuffers=function(){var curtains=this._curtains;var gl=curtains.gl;if(this._vao){if(curtains._isWebGL2){curtains.gl.bindVertexArray(this._vao);}
else{curtains._extensions['OES_vertex_array_object'].bindVertexArrayOES(this._vao);}}
else{gl.enableVertexAttribArray(this._attributes.vertexPosition.location);gl.bindBuffer(gl.ARRAY_BUFFER,this._geometry.bufferInfos.id);gl.vertexAttribPointer(this._attributes.vertexPosition.location,this._geometry.bufferInfos.itemSize,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(this._attributes.textureCoord.location);gl.bindBuffer(gl.ARRAY_BUFFER,this._material.bufferInfos.id);gl.vertexAttribPointer(this._attributes.textureCoord.location,this._material.bufferInfos.itemSize,gl.FLOAT,false,0,0);}
curtains._glState.currentBuffersID=this._definition.buffersID;};Curtains.BasePlane.prototype._bindPlaneTexture=function(texture){var gl=this._curtains.gl;if(texture._canDraw){gl.activeTexture(gl.TEXTURE0+texture.index);gl.bindTexture(gl.TEXTURE_2D,texture._sampler.texture);}};Curtains.BasePlane.prototype.setRenderTarget=function(renderTarget){if(!renderTarget||!renderTarget._type||renderTarget._type!=="RenderTarget"){if(!this._curtains.productionMode){console.warn("Could not set the render target because the argument passed is not a RenderTarget class object",renderTarget);}
return;}
this.target=renderTarget;};Curtains.BasePlane.prototype._drawPlane=function(){var curtains=this._curtains;var gl=curtains.gl;if(this._canDraw){if(this._onRenderCallback){this._onRenderCallback();}
if(this._type==="ShaderPass"){if(this._isScenePass){if(curtains._glState.scenePassIndex+1<curtains._drawStacks.scenePasses.length){curtains._bindFrameBuffer(curtains.shaderPasses[curtains._drawStacks.scenePasses[curtains._glState.scenePassIndex+1]].target);curtains._glState.scenePassIndex++;}
else{curtains._bindFrameBuffer(null);}}
else if(curtains._glState.scenePassIndex===null){curtains._bindFrameBuffer(null);}}
else{if(this.target){curtains._bindFrameBuffer(this.target);}
else if(curtains._glState.scenePassIndex===null){curtains._bindFrameBuffer(null);}
this._setPerspectiveMatrix();this._setMVMatrix();}
if((this.alwaysDraw||this._shouldDraw)&&this.visible){curtains._setDepth(this._depthTest);curtains._setFaceCulling(this.cullFace);curtains._useProgram(this._usedProgram);this._updateUniforms();if(curtains._glState.currentBuffersID!==this._definition.buffersID||this.target){this._bindPlaneBuffers();}
for(var i=0;i<this.textures.length;i++){this.textures[i]._drawTexture();}
gl.drawArrays(gl.TRIANGLES,0,this._geometry.bufferInfos.numberOfItems);if(this._onAfterRenderCallback){this._onAfterRenderCallback();}}}};Curtains.BasePlane.prototype._dispose=function(){var gl=this._curtains.gl;if(gl){if(this._vao){if(this._curtains._isWebGL2){gl.deleteVertexArray(this._vao);}
else{this._curtains._extensions['OES_vertex_array_object'].deleteVertexArrayOES(this._vao);}}
if(this._geometry){gl.bindBuffer(gl.ARRAY_BUFFER,this._geometry.bufferInfos.id);gl.bufferData(gl.ARRAY_BUFFER,1,gl.STATIC_DRAW);gl.deleteBuffer(this._geometry.bufferInfos.id);this._geometry=null;}
if(this._material){gl.bindBuffer(gl.ARRAY_BUFFER,this._material.bufferInfos.id);gl.bufferData(gl.ARRAY_BUFFER,1,gl.STATIC_DRAW);gl.deleteBuffer(this._material.bufferInfos.id);this._material=null;}
if(this.target&&this._type==="ShaderPass"){this._curtains.removeRenderTarget(this.target);this.textures.shift();}
for(var i=0;i<this.textures.length;i++){this.textures[i]._dispose();}
this.textures=null;}};Curtains.BasePlane.prototype.onAfterResize=function(callback){if(callback){this._onAfterResizeCallback=callback;}
return this;};Curtains.BasePlane.prototype.onLoading=function(callback){if(callback){this._onPlaneLoadingCallback=callback;}
return this;};Curtains.BasePlane.prototype.onReady=function(callback){if(callback){this._onReadyCallback=callback;}
return this;};Curtains.BasePlane.prototype.onRender=function(callback){if(callback){this._onRenderCallback=callback;}
return this;};Curtains.BasePlane.prototype.onAfterRender=function(callback){if(callback){this._onAfterRenderCallback=callback;}
return this;};Curtains.Plane=function(curtainWrapper,plane,params){this._type="Plane";Curtains.BasePlane.call(this,curtainWrapper,plane,params);this.index=this._curtains.planes.length;this._canDraw=false;this.target=null;if(!params)params={};this._setInitParams(params);if(this._usedProgram){this._curtains._stackPlane(this);this._initPositions();this._initSources();}
else{if(this._curtains._onErrorCallback){this._curtains._onErrorCallback();}}};Curtains.Plane.prototype=Object.create(Curtains.BasePlane.prototype);Curtains.Plane.prototype.constructor=Curtains.Plane;Curtains.Plane.prototype._setInitParams=function(params){this.alwaysDraw=params.alwaysDraw||false;this._transparent=params.transparent||false;var drawCheckMargins={top:0,right:0,bottom:0,left:0,};if(params.drawCheckMargins){drawCheckMargins=params.drawCheckMargins;}
this.drawCheckMargins=drawCheckMargins;this._initTransformValues();this.autoloadSources=params.autoloadSources;if(this.autoloadSources===null||this.autoloadSources===undefined){this.autoloadSources=true;}
this._fov=params.fov||50;this._nearPlane=0.1;this._farPlane=150;if(params.watchScroll===null||params.watchScroll===undefined){this.watchScroll=this._curtains._watchScroll;}
else{this.watchScroll=params.watchScroll||false;}
if(this.watchScroll){this._curtains._scrollManager.shouldWatch=true;}};Curtains.Plane.prototype._initTransformValues=function(){this.rotation={x:0,y:0,z:0,};this.quaternion=new Float32Array([0,0,0,1]);this.relativeTranslation={x:0,y:0,z:0,};this._translation={x:0,y:0,z:0};this.scale={x:1,y:1,};this.transformOrigin={x:0.5,y:0.5,z:0,};};Curtains.Plane.prototype._initPositions=function(){this._initMatrices();this.setPerspective(this._fov,this._nearPlane,this._farPlane);this._applyWorldPositions();};Curtains.Plane.prototype._initSources=function(){if(this.autoloadSources){var imagesArray=[];for(var i=0;i<this.htmlElement.getElementsByTagName("img").length;i++){imagesArray.push(this.htmlElement.getElementsByTagName("img")[i]);}
if(imagesArray.length>0){this.loadSources(imagesArray);}
var videosArray=[];for(var i=0;i<this.htmlElement.getElementsByTagName("video").length;i++){videosArray.push(this.htmlElement.getElementsByTagName("video")[i]);}
if(videosArray.length>0){this.loadSources(videosArray);}
var canvasesArray=[];for(var i=0;i<this.htmlElement.getElementsByTagName("canvas").length;i++){canvasesArray.push(this.htmlElement.getElementsByTagName("canvas")[i]);}
if(canvasesArray.length>0){this.loadSources(canvasesArray);}
this._loadingManager.initSourcesToLoad=imagesArray.length+videosArray.length+canvasesArray.length;}
if(this._loadingManager.initSourcesToLoad===0){this._isPlaneReady();if(!this._curtains.productionMode){console.warn("This plane does not contain any image, video or canvas element. You may want to add some later with the loadSource() or loadSources() method.");}}
this._canDraw=true;this._curtains.needRender();if(!this.alwaysDraw){this._shouldDrawCheck();}};Curtains.Plane.prototype._initMatrices=function(){var gl=this._curtains.gl;this._matrices={mvMatrix:{name:"uMVMatrix",matrix:new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),location:gl.getUniformLocation(this._usedProgram.program,"uMVMatrix"),},pMatrix:{name:"uPMatrix",matrix:new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),location:gl.getUniformLocation(this._usedProgram.program,"uPMatrix"),}};};Curtains.Plane.prototype.resetPlane=function(htmlElement){this._initTransformValues();if(htmlElement!==null&&!!htmlElement){this.htmlElement=htmlElement;this.updatePosition();}
else if(!htmlElement&&!this._curtains.productionMode){console.warn("You are trying to reset a plane with a HTML element that does not exist. The old HTML element will be kept instead.");}};Curtains.Plane.prototype._setWorldSizes=function(){var curtains=this._curtains;var planeCenter={x:(this._boundingRect.document.width / 2)+this._boundingRect.document.left,y:(this._boundingRect.document.height / 2)+this._boundingRect.document.top,};var curtainsCenter={x:(curtains._boundingRect.width / 2)+curtains._boundingRect.left,y:(curtains._boundingRect.height / 2)+curtains._boundingRect.top,};this._boundingRect.world={width:this._boundingRect.document.width / curtains._boundingRect.width,height:this._boundingRect.document.height / curtains._boundingRect.height,top:(curtainsCenter.y-planeCenter.y)/ curtains._boundingRect.height,left:(planeCenter.x-curtainsCenter.x)/ curtains._boundingRect.height,};this._boundingRect.world.scale={x:(this._curtains._boundingRect.width / this._curtains._boundingRect.height)*this._boundingRect.world.width / 2,y:this._boundingRect.world.height / 2,};};Curtains.Plane.prototype._setPerspectiveMatrix=function(){if(this._updatePerspectiveMatrix){var aspect=this._curtains._boundingRect.width / this._curtains._boundingRect.height;var top=this._nearPlane*Math.tan((Math.PI / 180)*0.5*this._fov);var height=2*top;var width=aspect*height;var left=-0.5*width;var right=left+width;var bottom=top-height;var x=2*this._nearPlane /(right-left);var y=2*this._nearPlane /(top-bottom);var a=(right+left)/(right-left);var b=(top+bottom)/(top-bottom);var c=-(this._farPlane+this._nearPlane)/(this._farPlane-this._nearPlane);var d=-2*this._farPlane*this._nearPlane /(this._farPlane-this._nearPlane);this._matrices.pMatrix.matrix=new Float32Array([x,0,0,0,0,y,0,0,a,b,c,-1,0,0,d,0]);}
if(this.shareProgram||!this.shareProgram&&this._updatePerspectiveMatrix){this._curtains._useProgram(this._usedProgram);this._curtains.gl.uniformMatrix4fv(this._matrices.pMatrix.location,false,this._matrices.pMatrix.matrix);}
this._updatePerspectiveMatrix=false;};Curtains.Plane.prototype.setPerspective=function(fov,near,far){var fieldOfView=isNaN(fov)?this._fov:parseFloat(fov);fieldOfView=Math.max(1,Math.min(fieldOfView,179));if(fieldOfView!==this._fov){this._fov=fieldOfView;}
this._cameraZPosition=Math.tan((Math.PI / 180)*0.5*this._fov)*2.0;this._CSSPerspective=Math.pow(Math.pow(this._curtains._boundingRect.width /(2*this._curtains.pixelRatio),2)+Math.pow(this._curtains._boundingRect.height /(2*this._curtains.pixelRatio),2),0.5)/ Math.tan((this._fov / 2)*Math.PI / 180);this._nearPlane=isNaN(near)?this._nearPlane:parseFloat(near);this._nearPlane=Math.max(this._nearPlane,0.01);this._farPlane=isNaN(far)?this._farPlane:parseFloat(far);this._farPlane=Math.max(this._farPlane,50);this._updatePerspectiveMatrix=true;this._updateMVMatrix=true;};Curtains.Plane.prototype._setMVMatrix=function(){if(this._updateMVMatrix){this._translation.z=this.relativeTranslation.z / this._CSSPerspective;var translation={x:this._translation.x,y:this._translation.y,z:-((1-this._translation.z)/ this._cameraZPosition),};var adjustedOrigin={x:this.transformOrigin.x*2-1,y:-(this.transformOrigin.y*2-1),};var origin={x:adjustedOrigin.x*this._boundingRect.world.scale.x,y:adjustedOrigin.y*this._boundingRect.world.scale.y,z:this.transformOrigin.z};var matrixFromOrigin=this._curtains._composeMatrixFromOrigin(translation,this.quaternion,this.scale,origin);var scaleMatrix=new Float32Array([this._boundingRect.world.scale.x,0.0,0.0,0.0,0.0,this._boundingRect.world.scale.y,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0]);this._matrices.mvMatrix.matrix=this._curtains._multiplyMatrix(matrixFromOrigin,scaleMatrix);this._matrices.mVPMatrix=this._curtains._multiplyMatrix(this._matrices.pMatrix.matrix,this._matrices.mvMatrix.matrix);if(!this.alwaysDraw){this._shouldDrawCheck();}}
if(this.shareProgram||!this.shareProgram&&this._updateMVMatrix){this._curtains._useProgram(this._usedProgram);this._curtains.gl.uniformMatrix4fv(this._matrices.mvMatrix.location,false,this._matrices.mvMatrix.matrix);}
this._updateMVMatrix=false;};Curtains.Plane.prototype.setScale=function(scaleX,scaleY){scaleX=isNaN(scaleX)?this.scale.x:parseFloat(scaleX);scaleY=isNaN(scaleY)?this.scale.y:parseFloat(scaleY);scaleX=Math.max(scaleX,0.001);scaleY=Math.max(scaleY,0.001);if(scaleX!==this.scale.x||scaleY!==this.scale.y){this.scale={x:scaleX,y:scaleY};for(var i=0;i<this.textures.length;i++){this.textures[i].resize();}
this._updateMVMatrix=true;}};Curtains.Plane.prototype.setRotation=function(angleX,angleY,angleZ){angleX=isNaN(angleX)?this.rotation.x:parseFloat(angleX);angleY=isNaN(angleY)?this.rotation.y:parseFloat(angleY);angleZ=isNaN(angleZ)?this.rotation.z:parseFloat(angleZ);if(angleX!==this.rotation.x||angleY!==this.rotation.y||angleZ!==this.rotation.z){this.rotation={x:angleX,y:angleY,z:angleZ};this._setQuaternion();this._updateMVMatrix=true;}};Curtains.Plane.prototype._setQuaternion=function(){var ax=this.rotation.x*0.5;var ay=this.rotation.y*0.5;var az=this.rotation.z*0.5;var sinx=Math.sin(ax);var cosx=Math.cos(ax);var siny=Math.sin(ay);var cosy=Math.cos(ay);var sinz=Math.sin(az);var cosz=Math.cos(az);this.quaternion[0]=sinx*cosy*cosz+cosx*siny*sinz;this.quaternion[1]=cosx*siny*cosz-sinx*cosy*sinz;this.quaternion[2]=cosx*cosy*sinz+sinx*siny*cosz;this.quaternion[3]=cosx*cosy*cosz-sinx*siny*sinz;};Curtains.Plane.prototype.setTransformOrigin=function(xOrigin,yOrigin,zOrigin){xOrigin=isNaN(xOrigin)?this.transformOrigin.x:parseFloat(xOrigin);yOrigin=isNaN(yOrigin)?this.transformOrigin.y:parseFloat(yOrigin);zOrigin=isNaN(zOrigin)?this.transformOrigin.z:parseFloat(zOrigin);if(xOrigin!==this.transformOrigin.x||yOrigin!==this.transformOrigin.y||zOrigin!==this.transformOrigin.z){this.transformOrigin={x:xOrigin,y:yOrigin,z:zOrigin,};this._updateMVMatrix=true;}};Curtains.Plane.prototype._setTranslation=function(){var relativePosition={x:0,y:0,z:0,};if(this.relativeTranslation.x!==0||this.relativeTranslation.y!==0||this.relativeTranslation.z!==0){relativePosition=this._documentToLocalSpace(this.relativeTranslation.x,this.relativeTranslation.y);}
this._translation.x=this._boundingRect.world.left+relativePosition.x;this._translation.y=this._boundingRect.world.top+relativePosition.y;this._updateMVMatrix=true;};Curtains.Plane.prototype.setRelativePosition=function(translationX,translationY,translationZ){translationX=isNaN(translationX)?this.relativeTranslation.x:parseFloat(translationX);translationY=isNaN(translationY)?this.relativeTranslation.y:parseFloat(translationY);translationZ=isNaN(translationZ)?this.relativeTranslation.z:parseFloat(translationZ);if(translationX!==this.relativeTranslation.x||translationY!==this.relativeTranslation.y||translationZ!==this.relativeTranslation.z){this.relativeTranslation={x:translationX,y:translationY,z:translationZ,};this._setTranslation();}};Curtains.Plane.prototype._documentToLocalSpace=function(xPosition,yPosition){var relativePosition={x:xPosition /(this._curtains._boundingRect.width / this._curtains.pixelRatio)*(this._curtains._boundingRect.width / this._curtains._boundingRect.height),y:-yPosition /(this._curtains._boundingRect.height / this._curtains.pixelRatio),};return relativePosition;};Curtains.Plane.prototype._shouldDrawCheck=function(){var actualPlaneBounds=this._getWebGLDrawRect();var self=this;if(Math.round(actualPlaneBounds.right)<=this._curtains._boundingRect.left||Math.round(actualPlaneBounds.left)>=this._curtains._boundingRect.left+this._curtains._boundingRect.width||Math.round(actualPlaneBounds.bottom)<=this._curtains._boundingRect.top||Math.round(actualPlaneBounds.top)>=this._curtains._boundingRect.top+this._curtains._boundingRect.height){if(this._shouldDraw){this._shouldDraw=false;setTimeout(function(){if(self._onLeaveViewCallback){self._onLeaveViewCallback();}},0);}}
else{if(!this._shouldDraw){setTimeout(function(){if(self._onReEnterViewCallback){self._onReEnterViewCallback();}},0);}
this._shouldDraw=true;}};Curtains.Plane.prototype.isDrawn=function(){return this._canDraw&&this.visible&&(this._shouldDraw||this.alwaysDraw);};Curtains.Plane.prototype._applyWorldPositions=function(){this._setWorldSizes();this._setTranslation();};Curtains.Plane.prototype.updatePosition=function(){this._setDocumentSizes();this._applyWorldPositions();};Curtains.Plane.prototype.updateScrollPosition=function(){if(this._curtains._scrollManager.lastXDelta||this._curtains._scrollManager.lastYDelta){this._boundingRect.document.top+=this._curtains._scrollManager.lastYDelta*this._curtains.pixelRatio;this._boundingRect.document.left+=this._curtains._scrollManager.lastXDelta*this._curtains.pixelRatio;this._applyWorldPositions();}};Curtains.Plane.prototype.enableDepthTest=function(shouldEnableDepthTest){this._depthTest=shouldEnableDepthTest;};Curtains.Plane.prototype.moveToFront=function(){this.enableDepthTest(false);var drawType=this._transparent?"transparent":"opaque";var drawStack=this._curtains._drawStacks[drawType]["programs"]["program-"+this._usedProgram.id];for(var i=0;i<drawStack.length;i++){if(this.index===drawStack[i]){drawStack.splice(i,1);}}
if(drawType==="transparent"){drawStack.unshift(this.index);}
else{drawStack.push(this.index);}
this._curtains._drawStacks[drawType]["programs"]["program-"+this._usedProgram.id]=drawStack;for(var i=0;i<this._curtains._drawStacks[drawType]["order"].length;i++){if(this._curtains._drawStacks[drawType]["order"][i]===this._usedProgram.id){this._curtains._drawStacks[drawType]["order"].splice(i,1);}}
this._curtains._drawStacks[drawType]["order"].push(this._usedProgram.id);};Curtains.Plane.prototype.onReEnterView=function(callback){if(callback){this._onReEnterViewCallback=callback;}
return this;};Curtains.Plane.prototype.onLeaveView=function(callback){if(callback){this._onLeaveViewCallback=callback;}
return this;};Curtains.RenderTarget=function(curtainWrapper,params){if(!params)params={};this._curtains=curtainWrapper;this.index=this._curtains.renderTargets.length;this._type="RenderTarget";this._shaderPass=params.shaderPass||null;this._depth=params.depth||false;this._shouldClear=params.clear;if(this._shouldClear===null||this._shouldClear===undefined){this._shouldClear=true;}
this._minSize={width:params.minWidth||1024*this._curtains.pixelRatio,height:params.minHeight||1024*this._curtains.pixelRatio,};this.userData={};this.uuid=this._curtains._generateUUID();this._curtains.renderTargets.push(this);this._initRenderTarget();};Curtains.RenderTarget.prototype._initRenderTarget=function(){this._setSize();this.textures=[];this._createFrameBuffer();};Curtains.RenderTarget.prototype._setSize=function(){if(this._shaderPass&&this._shaderPass._isScenePass){this._size={width:this._curtains._boundingRect.width,height:this._curtains._boundingRect.height,};}
else{this._size={width:Math.max(this._minSize.width,this._curtains._boundingRect.width),height:Math.max(this._minSize.height,this._curtains._boundingRect.height),};}};Curtains.RenderTarget.prototype.resize=function(){if(this._shaderPass&&this._shaderPass._isScenePass){this._setSize();this._curtains._bindFrameBuffer(this,true);if(this._depth){this._bindDepthBuffer();}
this._curtains._bindFrameBuffer(null);}};Curtains.RenderTarget.prototype._bindDepthBuffer=function(){var gl=this._curtains.gl;if(this._depthBuffer){gl.bindRenderbuffer(gl.RENDERBUFFER,this._depthBuffer);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,this._size.width,this._size.height);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,this._depthBuffer);}};Curtains.RenderTarget.prototype._createFBOTexture=function(){var gl=this._curtains.gl;if(this.textures.length>0){this.textures[0]._canDraw=false;this.textures[0]._init();}
else{var texture=new Curtains.Texture(this._shaderPass?this._shaderPass:this,{index:this.textures.length,sampler:"uRenderTexture",isFBOTexture:true,});this.textures.push(texture);}
gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.textures[0]._sampler.texture,0);};Curtains.RenderTarget.prototype._createFrameBuffer=function(){var gl=this._curtains.gl;this._frameBuffer=gl.createFramebuffer();this._curtains._bindFrameBuffer(this,true);this._createFBOTexture();if(this._depth){this._depthBuffer=gl.createRenderbuffer();this._bindDepthBuffer();}
this._curtains._bindFrameBuffer(null);};Curtains.RenderTarget.prototype._restoreContext=function(){if(!this._shaderPass||!this._shaderPass._isScenePass){this._shaderPass=null;this._createFrameBuffer();}};Curtains.RenderTarget.prototype._dispose=function(){if(this._frameBuffer){this._curtains.gl.deleteFramebuffer(this._frameBuffer);this._frameBuffer=null;}
if(this._depthBuffer){this._curtains.gl.deleteRenderbuffer(this._depthBuffer);this._depthBuffer=null;}
this.textures[0]._dispose();this.textures=[];};Curtains.ShaderPass=function(curtainWrapper,params){if(!params)params={};params.widthSegments=1;params.heightSegments=1;this._type="ShaderPass";this._isScenePass=true;Curtains.BasePlane.call(this,curtainWrapper,curtainWrapper.container,params);this.index=this._curtains.shaderPasses.length;this._depth=params.depth||false;this._shouldClear=params.clear;if(this._shouldClear===null||this._shouldClear===undefined){this._shouldClear=true;}
this.target=params.renderTarget||null;if(this.target){this._isScenePass=false;this._shouldClear=this.target._shouldClear;}
if(this._usedProgram){this._initShaderPassPlane();}};Curtains.ShaderPass.prototype=Object.create(Curtains.BasePlane.prototype);Curtains.ShaderPass.prototype.constructor=Curtains.ShaderPass;Curtains.ShaderPass.prototype._initShaderPassPlane=function(){if(!this.target){this._createFrameBuffer();}
else{this.setRenderTarget(this.target);this.target._shaderPass=this;var texture=new Curtains.Texture(this,{index:this.textures.length,sampler:"uRenderTexture",isFBOTexture:true,fromTexture:this.target.textures[0],});this.textures.push(texture);}
this._isPlaneReady();this._canDraw=true;this._curtains.needRender();};Curtains.ShaderPass.prototype._getDefaultVS=function(params){return"precision mediump float;\nattribute vec3 aVertexPosition;attribute vec2 aTextureCoord;varying vec3 vVertexPosition;varying vec2 vTextureCoord;void main() {vTextureCoord = aTextureCoord;vVertexPosition = aVertexPosition;gl_Position = vec4(aVertexPosition, 1.0);}";};Curtains.ShaderPass.prototype._getDefaultFS=function(params){return"precision mediump float;\nvarying vec3 vVertexPosition;varying vec2 vTextureCoord;uniform sampler2D uRenderTexture;void main( void ) {gl_FragColor = texture2D(uRenderTexture, vTextureCoord);}";};Curtains.ShaderPass.prototype._createFrameBuffer=function(){var target=new Curtains.RenderTarget(this._curtains,{shaderPass:this,clear:this._shouldClear,depth:this._depth,});this.setRenderTarget(target);this.textures.push(this.target.textures[0]);};Curtains.Texture=function(parent,params){this._parent=parent;this._curtains=parent._curtains;this.uuid=this._curtains._generateUUID();if(!parent._usedProgram&&!params.isFBOTexture){if(!this._curtains.productionMode){console.warn("Unable to create the texture because the program is not valid");}
return;}
this.index=parent.textures.length;this._sampler={isActive:false,name:params.sampler||"uSampler"+this.index};this._textureMatrix={name:params.sampler?params.sampler+"Matrix":"uTextureMatrix"+this.index,matrix:null,};this._willUpdate=false;this.shouldUpdate=false;this._forceUpdate=false;this.scale={x:1,y:1,};this.userData={};this.type=params.isFBOTexture?"fboTexture":"empty";this._canDraw=false;if(params.fromTexture){this._initFromTexture=true;if(this._parent._usedProgram){this._setTextureUniforms();}
this.setFromTexture(params.fromTexture);return;}
this._initFromTexture=false;this._init();return this;};Curtains.Texture.prototype._init=function(){var gl=this._curtains.gl;this._sampler.texture=gl.createTexture();this._internalFormat=gl.RGBA;this._format=gl.RGBA;this._textureType=gl.UNSIGNED_BYTE;this._texParameters=false;this._flipY=false;gl.bindTexture(gl.TEXTURE_2D,this._sampler.texture);if(this._curtains._glState.flipY){this._curtains._glState.flipY=this._flipY;gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,this._flipY);}
gl.pixelStorei(gl.UNPACK_ALIGNMENT,4);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,false);if(this._parent._usedProgram){this._size={width:this._parent._boundingRect.document.width,height:this._parent._boundingRect.document.height,};this._setTextureUniforms();if(this.type==="empty"){gl.texImage2D(gl.TEXTURE_2D,0,this._internalFormat,1,1,0,this._format,this._textureType,new Uint8Array([0,0,0,255]));this._sourceLoaded=false;}
else if(!this.source){var sizes=this._getSizes();this._updateTextureMatrix(sizes);}}
else{this._size={width:this._parent._size.width||this._curtains._boundingRect.width,height:this._parent._size.height||this._curtains._boundingRect.height,};}
if(this.type==="fboTexture"){if(this._curtains._isWebGL2&&this._curtains._extensions['EXT_color_buffer_float']){this._internalFormat=gl.RGBA16F;this._textureType=gl.HALF_FLOAT;}
else if(this._curtains._extensions['OES_texture_half_float']){this._textureType=this._curtains._extensions['OES_texture_half_float'].HALF_FLOAT_OES;}
gl.texImage2D(gl.TEXTURE_2D,0,this._internalFormat,this._size.width,this._size.height,0,this._format,this._textureType,null);this._setMipmaps();}
this._canDraw=true;};Curtains.Texture.prototype._setTextureUniforms=function(){for(var i=0;i<this._parent._activeTextures.length;i++){if(this._parent._activeTextures[i].name===this._sampler.name){this._sampler.isActive=true;this._sampler.location=this._curtains.gl.getUniformLocation(this._parent._usedProgram.program,this._sampler.name);this._textureMatrix.location=this._curtains.gl.getUniformLocation(this._parent._usedProgram.program,this._textureMatrix.name);this._curtains._useProgram(this._parent._usedProgram);this._curtains.gl.uniform1i(this._sampler.location,this.index);}}};Curtains.Texture.prototype.setFromTexture=function(texture){if(texture){this.type=texture.type;this._sampler.texture=texture._sampler.texture;this.source=texture.source;this._size=texture._size;this._sourceLoaded=texture._sourceLoaded;this._internalFormat=texture._internalFormat;this._format=texture._format;this._textureType=texture._textureType;this._texParameters=texture._texParameters;this._originalTexture=texture;if(this._parent._usedProgram&&(!this._canDraw||!this._textureMatrix.matrix)){var sizes=this._getSizes();this._updateTextureMatrix(sizes);this._canDraw=true;}}
else if(!this._curtains.productionMode){console.warn("Unable to set the texture from texture:",texture);}};Curtains.Texture.prototype.setSource=function(source){if(!this._parent._usedProgram){if(!this._curtains.productionMode){console.warn("Unable to set the texture source because the program is not valid");}
return;}
this.source=source;if(this.type==="empty"){if(source.tagName.toUpperCase()==="IMG"){this.type="image";}
else if(source.tagName.toUpperCase()==="VIDEO"){this.type="video";this.shouldUpdate=true;}
else if(source.tagName.toUpperCase()==="CANVAS"){this.type="canvas";this._willUpdate=true;this.shouldUpdate=true;}
else if(!this._curtains.productionMode){console.warn("this HTML tag could not be converted into a texture:",source.tagName);}}
this._size={width:this.source.naturalWidth||this.source.width||this.source.videoWidth,height:this.source.naturalHeight||this.source.height||this.source.videoHeight,};this._sourceLoaded=true;var gl=this._curtains.gl;gl.activeTexture(gl.TEXTURE0+this.index);gl.bindTexture(gl.TEXTURE_2D,this._sampler.texture);if(this._curtains.premultipliedAlpha){gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,true);}
this._flipY=true;if(!this._curtains._glState.flipY){this._curtains._glState.flipY=this._flipY;gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,this._flipY);}
this.resize();if(this.type==="image"){gl.texImage2D(gl.TEXTURE_2D,0,this._internalFormat,this._format,this._textureType,source);this._setMipmaps();}
this._curtains.needRender();};Curtains.Texture.prototype._setMipmaps=function(){var gl=this._curtains.gl;gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);if(this._curtains._isWebGL2&&this.type==="image"){gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_NEAREST);}
else{gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);}
this._texParameters=true;};Curtains.Texture.prototype.needUpdate=function(){this._forceUpdate=true;};Curtains.Texture.prototype._update=function(){var gl=this._curtains.gl;if(this.source){gl.texImage2D(gl.TEXTURE_2D,0,this._internalFormat,this._format,this._textureType,this.source);if(!this._texParameters){this._setMipmaps();}}
else{gl.texImage2D(gl.TEXTURE_2D,0,this._internalFormat,this._size.width,this._size.height,0,this._format,this._textureType,this.source);}};Curtains.Texture.prototype._getSizes=function(){var scale=this._parent.scale?this._parent.scale:{x:1,y:1};var parentWidth=this._parent._boundingRect.document.width*scale.x;var parentHeight=this._parent._boundingRect.document.height*scale.y;var sourceWidth=this._size.width;var sourceHeight=this._size.height;var sourceRatio=sourceWidth / sourceHeight;var parentRatio=parentWidth / parentHeight;var xOffset=0;var yOffset=0;if(parentRatio>sourceRatio){yOffset=Math.min(0,parentHeight-(parentWidth*(1 / sourceRatio)));}
else if(parentRatio<sourceRatio){xOffset=Math.min(0,parentWidth-(parentHeight*sourceRatio));}
return{parentWidth:parentWidth,parentHeight:parentHeight,sourceWidth:sourceWidth,sourceHeight:sourceHeight,xOffset:xOffset,yOffset:yOffset,};};Curtains.Texture.prototype.setScale=function(scaleX,scaleY){scaleX=isNaN(scaleX)?this.scale.x:parseFloat(scaleX);scaleY=isNaN(scaleY)?this.scale.y:parseFloat(scaleY);scaleX=Math.max(scaleX,0.001);scaleY=Math.max(scaleY,0.001);if(scaleX!==this.scale.x||scaleY!==this.scale.y){this.scale={x:scaleX,y:scaleY,};this.resize();}};Curtains.Texture.prototype.resize=function(){if(this.type==="fboTexture"){var gl=this._curtains.gl;this._size={width:this._parent._boundingRect.document.width,height:this._parent._boundingRect.document.height,};if(!this._originalTexture){gl.bindTexture(gl.TEXTURE_2D,this._parent.textures[0]._sampler.texture);gl.texImage2D(gl.TEXTURE_2D,0,this._internalFormat,this._size.width,this._size.height,0,this._format,this._textureType,this.source);}}
else if(this.source){this._size={width:this.source.naturalWidth||this.source.width||this.source.videoWidth,height:this.source.naturalHeight||this.source.height||this.source.videoHeight,};}
if(this._parent._usedProgram){var sizes=this._getSizes();this._updateTextureMatrix(sizes);}};Curtains.Texture.prototype._updateTextureMatrix=function(sizes){var texScale={x:sizes.parentWidth /(sizes.parentWidth-sizes.xOffset),y:sizes.parentHeight /(sizes.parentHeight-sizes.yOffset),};texScale.x /=this.scale.x;texScale.y /=this.scale.y;var textureTranslation=new Float32Array([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,(1-texScale.x)/ 2,(1-texScale.y)/ 2,0.0,1.0]);this._textureMatrix.matrix=this._curtains._scaleMatrix(textureTranslation,texScale.x,texScale.y,1);this._curtains._useProgram(this._parent._usedProgram);this._curtains.gl.uniformMatrix4fv(this._textureMatrix.location,false,this._textureMatrix.matrix);};Curtains.Texture.prototype._onSourceLoaded=function(source){this._parent._loadingManager.sourcesLoaded++;var self=this;if(!this._sourceLoaded){setTimeout(function(){if(self._parent._onPlaneLoadingCallback){self._parent._onPlaneLoadingCallback(self);}},0);}
this.setSource(source);this._parent._isPlaneReady();if(this.type==="image"){var shouldCache=true;for(var i=0;i<this._curtains._imageCache.length;i++){if(this._curtains._imageCache[i].source&&this._curtains._imageCache[i].source.src===source.src){shouldCache=false;}}
if(shouldCache){this._curtains._imageCache.push(this);}}};Curtains.Texture.prototype._onVideoLoadedData=function(video){if(!this._sourceLoaded){this._onSourceLoaded(video);}};Curtains.Texture.prototype._drawTexture=function(){if(this._sampler.isActive){this._parent._bindPlaneTexture(this);if(this._flipY&&!this._curtains._glState.flipY){this._curtains._glState.flipY=this._flipY;this._curtains.gl.pixelStorei(this._curtains.gl.UNPACK_FLIP_Y_WEBGL,this._flipY);}
if(this.type==="video"&&this.source&&this.source.readyState>=this.source.HAVE_CURRENT_DATA){this._willUpdate=true;}
if(this._forceUpdate||(this._willUpdate&&this.shouldUpdate)){this._update();}
if(this.type==="video"){this._willUpdate=false;}
this._forceUpdate=false;}};Curtains.Texture.prototype._restoreFromTexture=function(){if(this._initFromTexture){this._setTextureUniforms();}
else{this._init();}
this.setFromTexture(this._originalTexture);};Curtains.Texture.prototype._restoreContext=function(){this._canDraw=false;this._sampler.isActive=false;if(!this._originalTexture){this._init();if(this.source){if(this.type==="image"){this._curtains._imageCache.push(this);}
this.setSource(this.source);this.needUpdate();}}
else{var self=this;if(!this._originalTexture._canDraw){var textureReadyInterval=setInterval(function(){if(self._originalTexture._canDraw){self._restoreFromTexture();clearInterval(textureReadyInterval);}},16);}
else{setTimeout(function(){self._restoreFromTexture();},0);}}};Curtains.Texture.prototype._dispose=function(){if(this.type==="video"){this.source.removeEventListener("canplaythrough",this._onSourceLoadedHandler,false);this.source.removeEventListener("error",this._parent._sourceLoadError,false);this.source.pause();this.source.removeAttribute("src");this.source.load();this.source=null;}
else if(this.type==="canvas"){this.source.width=this.source.width;this.source=null;}
else if(this.type==="image"&&this._curtains._isDestroying){this.source.removeEventListener("load",this._onSourceLoadedHandler,false);this.source.removeEventListener("error",this._parent._sourceLoadError,false);this.source=null;}
var gl=this._curtains.gl;var shouldDelete=gl&&!this._originalTexture&&(this.type!=="image"||this._curtains._isDestroying);if(shouldDelete){gl.activeTexture(gl.TEXTURE0+this.index);gl.bindTexture(gl.TEXTURE_2D,null);gl.deleteTexture(this._sampler.texture);}
this._parent._loadingManager&&this._parent._loadingManager.sourcesLoaded--;};